import MoltResearch.Discrepancy.Unbounded
import MoltResearch.Discrepancy.AffineTail

/-!
# Tao 2015: Erdős discrepancy theorem (Track C skeleton)

This module is **Conjectures-only**: it may contain axiom stubs (and, if needed, `sorry`).

At present, the only non-verified assumption is the Stage-2 axiom in
`Conjectures.C0002_erdos_discrepancy.src.TrackCStage2Stub`.

Hard goal for Track C automation: make

`lake build Conjectures.C0002_erdos_discrepancy.src.ErdosDiscrepancy`

compile cleanly, while providing *typed stage interfaces* for the Tao 2015 proof pipeline.

Design principles:
- Keep the surface small and stable (records + a few normal-form predicates).
- Avoid lemma sprawl in `MoltResearch/` (verified substrate lives elsewhere).
- Prefer explicit stage boundaries (`ReductionOutput`, `Stage2Output`, `Stage3Output`).

Note: The previous version of this file accrued a lot of autogenerated glue and became
non-compiling (duplicate declarations + simp loops). This rewrite restores a minimal,
compiling interface.
-/

namespace MoltResearch

namespace Tao2015

set_option autoImplicit false

/-!
## Fixed-step discrepancy normal forms

These are the Track C “along a fixed step `d`” analogues of the global predicates in
`MoltResearch.Discrepancy.Unbounded`.
-/

/-- `g` has bounded discrepancy along the fixed step `d`. -/
def BoundedDiscrepancyAlong (g : ℕ → ℤ) (d : ℕ) : Prop :=
  ∃ B : ℕ, ∀ n : ℕ, discrepancy g d n ≤ B

/-- Nucleus normal form for `BoundedDiscrepancyAlong`.

Normal form:
`∃ B, ∀ n, Int.natAbs (apSum g d n) ≤ B`.

This is a lightweight rewrite of the definition of `BoundedDiscrepancyAlong` using the definitional
identity `discrepancy g d n = Int.natAbs (apSum g d n)`.
-/
theorem boundedDiscrepancyAlong_iff_exists_forall_natAbs_apSum_le (g : ℕ → ℤ) (d : ℕ) :
    BoundedDiscrepancyAlong g d ↔ (∃ B : ℕ, ∀ n : ℕ, Int.natAbs (apSum g d n) ≤ B) := by
  constructor
  · rintro ⟨B, hB⟩
    refine ⟨B, ?_⟩
    intro n
    have hn : discrepancy g d n ≤ B := hB n
    unfold discrepancy at hn
    exact hn
  · rintro ⟨B, hB⟩
    refine ⟨B, ?_⟩
    intro n
    have hn : Int.natAbs (apSum g d n) ≤ B := hB n
    unfold discrepancy
    exact hn

/-- `g` has unbounded discrepancy along the fixed step `d` (witness form). -/
def UnboundedDiscrepancyAlong (g : ℕ → ℤ) (d : ℕ) : Prop :=
  ∀ B : ℕ, ∃ n : ℕ, B < discrepancy g d n

/-- Negation-normal-form equivalence: fixed-step unboundedness is the negation of fixed-step boundedness.

This lemma is intentionally tiny but useful when stage boundaries trade between witness forms and
boundedness hypotheses.
-/
theorem unboundedDiscrepancyAlong_iff_not_boundedDiscrepancyAlong (g : ℕ → ℤ) (d : ℕ) :
    UnboundedDiscrepancyAlong g d ↔ ¬ BoundedDiscrepancyAlong g d := by
  classical
  constructor
  · intro hunb hbd
    rcases hbd with ⟨B, hB⟩
    rcases hunb B with ⟨n, hn⟩
    exact (not_lt_of_ge (hB n)) hn
  · intro hnot B
    by_contra hcontra
    have hle : ∀ n : ℕ, discrepancy g d n ≤ B := by
      intro n
      have hnotlt : ¬ B < discrepancy g d n := (not_exists.mp hcontra) n
      have hnotgt : ¬ discrepancy g d n > B := by
        simpa [gt_iff_lt] using hnotlt
      exact le_of_not_gt hnotgt
    exact hnot ⟨B, hle⟩

/-- Inequality-direction variant of `UnboundedDiscrepancyAlong`, written as `discrepancy ... > B`.

Many consumers prefer this normal form so they can `simp [gt_iff_lt]` at the call site.
-/
theorem unboundedDiscrepancyAlong_iff_forall_exists_discrepancy_gt' (g : ℕ → ℤ) (d : ℕ) :
    UnboundedDiscrepancyAlong g d ↔ (∀ B : ℕ, ∃ n : ℕ, discrepancy g d n > B) := by
  constructor
  · intro hunb B
    rcases hunb B with ⟨n, hn⟩
    exact ⟨n, hn⟩
  · intro h B
    rcases h B with ⟨n, hn⟩
    exact ⟨n, hn⟩

/-- Nucleus normal form for `UnboundedDiscrepancyAlong`.

Normal form:
`∀ B, ∃ n, Int.natAbs (apSum g d n) > B`.

This is a lightweight rewrite of `unboundedDiscrepancyAlong_iff_forall_exists_discrepancy_gt'`
using the definitional equality `discrepancy g d n = Int.natAbs (apSum g d n)`.
-/
theorem unboundedDiscrepancyAlong_iff_forall_exists_natAbs_apSum_gt' (g : ℕ → ℤ) (d : ℕ) :
    UnboundedDiscrepancyAlong g d ↔ (∀ B : ℕ, ∃ n : ℕ, Int.natAbs (apSum g d n) > B) := by
  constructor
  · intro hunb B
    rcases hunb B with ⟨n, hn⟩
    refine ⟨n, ?_⟩
    -- `discrepancy g d n` is definitionally `Int.natAbs (apSum g d n)`.
    unfold discrepancy at hn
    exact hn
  · intro h B
    rcases h B with ⟨n, hn⟩
    refine ⟨n, ?_⟩
    -- Unfold `discrepancy`, then use the nucleus witness.
    unfold discrepancy
    exact hn

namespace UnboundedDiscrepancyAlong

/-- Witness-positivity: in the unboundedness normal form
`∀ B, ∃ n, discrepancy g d n > B`, any witness length `n` is automatically positive.

Reason: `discrepancy g d 0 = 0`.
-/
theorem forall_exists_discrepancy_gt'_witness_pos {g : ℕ → ℤ} {d : ℕ}
    (hunb : UnboundedDiscrepancyAlong g d) :
    ∀ B : ℕ, ∃ n : ℕ, n > 0 ∧ discrepancy g d n > B := by
  intro B
  rcases
      (unboundedDiscrepancyAlong_iff_forall_exists_discrepancy_gt' (g := g) (d := d)).1 hunb B with
    ⟨n, hn⟩
  have hn0 : n ≠ 0 := by
    intro h0
    subst h0
    have hn0' : discrepancy g d 0 > B := hn
    -- `simp` turns the discrepancy witness into `False` (since `discrepancy g d 0 = 0`).
    simp [discrepancy_zero] at hn0'
  exact ⟨n, Nat.pos_of_ne_zero hn0, hn⟩

/-- Witness-positivity: nucleus form of unboundedness, with `Int.natAbs (apSum ...) > B`. -/
theorem forall_exists_natAbs_apSum_gt'_witness_pos {g : ℕ → ℤ} {d : ℕ}
    (hunb : UnboundedDiscrepancyAlong g d) :
    ∀ B : ℕ, ∃ n : ℕ, n > 0 ∧ Int.natAbs (apSum g d n) > B := by
  intro B
  rcases forall_exists_discrepancy_gt'_witness_pos (g := g) (d := d) hunb B with ⟨n, hnpos, hn⟩
  refine ⟨n, hnpos, ?_⟩
  -- Avoid simp loops: `discrepancy` is definitional.
  have hn' := hn
  unfold discrepancy at hn'
  exact hn'

end UnboundedDiscrepancyAlong

/-- `g` has discrepancy at least `C` along the fixed step `d` (witness form). -/
def HasDiscrepancyAtLeastAlong (g : ℕ → ℤ) (d : ℕ) (C : ℕ) : Prop :=
  ∃ n : ℕ, C < discrepancy g d n

/-- Inequality-direction variant of `HasDiscrepancyAtLeastAlong`, written as `discrepancy ... > C`.

Many consumers prefer this normal form so they can `simp [gt_iff_lt]` at the call site.
-/
theorem hasDiscrepancyAtLeastAlong_iff_exists_discrepancy_gt' (g : ℕ → ℤ) (d C : ℕ) :
    HasDiscrepancyAtLeastAlong g d C ↔ (∃ n : ℕ, discrepancy g d n > C) := by
  constructor
  · rintro ⟨n, hn⟩
    exact ⟨n, hn⟩
  · rintro ⟨n, hn⟩
    exact ⟨n, hn⟩

/-- Nucleus normal form for `HasDiscrepancyAtLeastAlong`.

Normal form:
`∃ n, Int.natAbs (apSum g d n) > C`.

This is a lightweight rewrite of `hasDiscrepancyAtLeastAlong_iff_exists_discrepancy_gt'` using the
definitional equality `discrepancy g d n = Int.natAbs (apSum g d n)`.
-/
theorem hasDiscrepancyAtLeastAlong_iff_exists_natAbs_apSum_gt' (g : ℕ → ℤ) (d C : ℕ) :
    HasDiscrepancyAtLeastAlong g d C ↔ (∃ n : ℕ, Int.natAbs (apSum g d n) > C) := by
  constructor
  · rintro ⟨n, hn⟩
    refine ⟨n, ?_⟩
    unfold discrepancy at hn
    exact hn
  · rintro ⟨n, hn⟩
    refine ⟨n, ?_⟩
    unfold discrepancy
    exact hn

/-- Unboundedness of a bundled offset discrepancy family. -/
def UnboundedDiscOffset (f : ℕ → ℤ) (d m : ℕ) : Prop :=
  ∀ B : ℕ, ∃ n : ℕ, B < discOffset f d m n

/-- Inequality-direction variant of `UnboundedDiscOffset`, written as `discOffset ... > B`.

Many consumers prefer this normal form so they can `simp [gt_iff_lt]` at the call site.
-/
theorem unboundedDiscOffset_iff_forall_exists_discOffset_gt' (f : ℕ → ℤ) (d m : ℕ) :
    UnboundedDiscOffset f d m ↔ (∀ B : ℕ, ∃ n : ℕ, discOffset f d m n > B) := by
  constructor
  · intro hunb B
    rcases hunb B with ⟨n, hn⟩
    exact ⟨n, hn⟩
  · intro h B
    rcases h B with ⟨n, hn⟩
    exact ⟨n, hn⟩

/-- Witness-positivity variant of `UnboundedDiscOffset`.

Since `discOffset f d m 0 = 0`, any witness satisfying `discOffset f d m n > B` must have
`n > 0`.

This is often the most convenient normal form for downstream stages that want to avoid reasoning
about the trivial `n = 0` case.
-/
theorem unboundedDiscOffset_iff_forall_exists_discOffset_gt'_witness_pos (f : ℕ → ℤ) (d m : ℕ) :
    UnboundedDiscOffset f d m ↔
      (∀ B : ℕ, ∃ n : ℕ, n > 0 ∧ discOffset f d m n > B) := by
  constructor
  · intro hunb B
    rcases hunb B with ⟨n, hn⟩
    have hn0 : n ≠ 0 := by
      intro h0
      subst h0
      have : ¬ B < discOffset f d m 0 := by
        simp
      exact this hn
    exact ⟨n, Nat.pos_of_ne_zero hn0, hn⟩
  · intro h B
    rcases h B with ⟨n, hnpos, hn⟩
    exact ⟨n, hn⟩

/-- Normal form: the affine-tail nucleus at start `m*d` is the bundled offset nucleus. -/
theorem apSumFrom_mul_eq_apSumOffset (f : ℕ → ℤ) (d m n : ℕ) :
    apSumFrom f (m * d) d n = apSumOffset f d m n := by
  calc
    apSumFrom f (m * d) d n = apSumFrom f (0 + m * d) d n := by
      simp
    _ = apSumOffset (fun k => f (k + 0)) d m n := by
      exact apSumFrom_tail_eq_apSumOffset_shift_add (f := f) (a := 0) (d := d) (m := m) (n := n)
    _ = apSumOffset f d m n := by
      simp

/-- Paper-notation normal form: the bundled offset nucleus `apSumOffset` is an interval sum.

This is a thin wrapper around `apSumOffset_eq_sum_Icc` (from `MoltResearch.Discrepancy`), with
`Int.natAbs` applied on both sides so it can be used directly in inequality goals.
-/
theorem natAbs_apSumOffset_eq_natAbs_sum_Icc (f : ℕ → ℤ) (d m n : ℕ) :
    Int.natAbs (apSumOffset f d m n) =
      Int.natAbs ((Finset.Icc (m + 1) (m + n)).sum (fun i => f (i * d))) := by
  -- Apply `Int.natAbs` to `apSumOffset_eq_sum_Icc` without invoking the simp engine.
  exact
    congrArg Int.natAbs (apSumOffset_eq_sum_Icc (f := f) (d := d) (m := m) (n := n))

/-- Paper-notation normal form: the bundled offset discrepancy wrapper `discOffset` is an interval sum.

This avoids having to unfold `discOffset` and then separately rewrite `apSumOffset` into an interval
sum.
-/
theorem discOffset_eq_natAbs_sum_Icc (f : ℕ → ℤ) (d m n : ℕ) :
    discOffset f d m n =
      Int.natAbs ((Finset.Icc (m + 1) (m + n)).sum (fun i => f (i * d))) := by
  -- `discOffset` is definitionally `Int.natAbs (apSumOffset ...)`.
  unfold discOffset
  exact natAbs_apSumOffset_eq_natAbs_sum_Icc (f := f) (d := d) (m := m) (n := n)

namespace UnboundedDiscOffset

/-- Witness-positivity: in the `∀ B, ∃ n, B < discOffset f d m n` unboundedness normal form,
any witness length `n` is automatically positive.

Reason: `discOffset f d m 0 = 0`, so `B < discOffset f d m 0` is impossible.
-/
theorem forall_exists_discOffset_gt_witness_pos {f : ℕ → ℤ} {d m : ℕ}
    (hunb : UnboundedDiscOffset f d m) :
    ∀ B : ℕ, ∃ n : ℕ, n > 0 ∧ B < discOffset f d m n := by
  intro B
  rcases hunb B with ⟨n, hn⟩
  have hn0 : n ≠ 0 := by
    intro h0
    subst h0
    have : ¬ B < discOffset f d m 0 := by
      simp
    exact this hn
  exact ⟨n, Nat.pos_of_ne_zero hn0, hn⟩

/-- Witness-positivity: in the inequality-direction unboundedness normal form
`∀ B, ∃ n, discOffset f d m n > B`, any witness length `n` is automatically positive.

This is `forall_exists_discOffset_gt_witness_pos` rewritten using `gt_iff_lt`.
-/
theorem forall_exists_discOffset_gt'_witness_pos {f : ℕ → ℤ} {d m : ℕ}
    (hunb : UnboundedDiscOffset f d m) :
    ∀ B : ℕ, ∃ n : ℕ, n > 0 ∧ discOffset f d m n > B := by
  intro B
  rcases forall_exists_discOffset_gt_witness_pos (f := f) (d := d) (m := m) hunb B with
    ⟨n, hnpos, hn⟩
  exact ⟨n, hnpos, (gt_iff_lt).2 hn⟩

/-- Witness-positivity: in the bundled-nucleus witness form
`∀ B, ∃ n, Int.natAbs (apSumOffset f d m n) > B`, any witness length `n` is automatically positive.

Reason: `apSumOffset f d m 0 = 0`.
-/
theorem forall_exists_natAbs_apSumOffset_gt_witness_pos {f : ℕ → ℤ} {d m : ℕ}
    (hunb : UnboundedDiscOffset f d m) :
    ∀ B : ℕ, ∃ n : ℕ, n > 0 ∧ Int.natAbs (apSumOffset f d m n) > B := by
  intro B
  rcases forall_exists_discOffset_gt_witness_pos (f := f) (d := d) (m := m) hunb B with
    ⟨n, hnpos, hn⟩
  refine ⟨n, hnpos, ?_⟩
  have hn' : B < Int.natAbs (apSumOffset f d m n) := by
    have hn' := hn
    unfold discOffset at hn'
    exact hn'
  exact (gt_iff_lt).2 hn'

/-- Witness-positivity normal form: unbounded offset discrepancy is equivalent to arbitrarily large
bundled offset nuclei, with witnesses `n > 0`.

This is `unboundedDiscOffset_iff_forall_exists_discOffset_gt'_witness_pos` rewritten using the
definitional equality `discOffset = Int.natAbs (apSumOffset ...)`.
-/
theorem iff_forall_exists_natAbs_apSumOffset_gt'_witness_pos (f : ℕ → ℤ) (d m : ℕ) :
    UnboundedDiscOffset f d m ↔
      (∀ B : ℕ, ∃ n : ℕ, n > 0 ∧ Int.natAbs (apSumOffset f d m n) > B) := by
  constructor
  · intro hunb B
    rcases
        (unboundedDiscOffset_iff_forall_exists_discOffset_gt'_witness_pos (f := f) (d := d) (m := m)).1
          hunb B with
      ⟨n, hnpos, hn⟩
    refine ⟨n, hnpos, ?_⟩
    have hn' := hn
    unfold discOffset at hn'
    exact hn'
  · intro h
    refine
      (unboundedDiscOffset_iff_forall_exists_discOffset_gt'_witness_pos (f := f) (d := d) (m := m)).2
        ?_
    intro B
    rcases h B with ⟨n, hnpos, hn⟩
    refine ⟨n, hnpos, ?_⟩
    unfold discOffset
    exact hn

/-- Normal form: unbounded offset discrepancy expressed directly using the bundled offset nucleus.

Since `discOffset f d m n` is definitionally `Int.natAbs (apSumOffset f d m n)`, this lemma lets
later stages avoid unfolding `discOffset` by hand.
-/
theorem iff_forall_exists_natAbs_apSumOffset_gt (f : ℕ → ℤ) (d m : ℕ) :
    UnboundedDiscOffset f d m ↔
      (∀ B : ℕ, ∃ n : ℕ, B < Int.natAbs (apSumOffset f d m n)) := by
  simp [UnboundedDiscOffset, discOffset, -natAbs_apSumOffset_eq_discOffset]

/-- Variant of `iff_forall_exists_natAbs_apSumOffset_gt` with the inequality written as
`Int.natAbs ... > B` (often the normal form used by Stage interfaces).
-/
theorem iff_forall_exists_natAbs_apSumOffset_gt' (f : ℕ → ℤ) (d m : ℕ) :
    UnboundedDiscOffset f d m ↔
      (∀ B : ℕ, ∃ n : ℕ, Int.natAbs (apSumOffset f d m n) > B) := by
  simpa [gt_iff_lt] using (iff_forall_exists_natAbs_apSumOffset_gt (f := f) (d := d) (m := m))

/-- Normal form: unbounded offset discrepancy expressed using affine-tail nuclei
`apSumFrom f (m*d) d n`.

This is a lightweight rewrite of `iff_forall_exists_natAbs_apSumOffset_gt` using the identity
`apSumFrom f (m*d) d n = apSumOffset f d m n`.
-/
theorem iff_forall_exists_natAbs_apSumFrom_mul_gt (f : ℕ → ℤ) (d m : ℕ) :
    UnboundedDiscOffset f d m ↔
      (∀ B : ℕ, ∃ n : ℕ, B < Int.natAbs (apSumFrom f (m * d) d n)) := by
  constructor
  · intro hunb B
    rcases (iff_forall_exists_natAbs_apSumOffset_gt (f := f) (d := d) (m := m)).1 hunb B with
      ⟨n, hn⟩
    refine ⟨n, ?_⟩
    have hsum : apSumOffset f d m n = apSumFrom f (m * d) d n := by
      simpa using (apSumFrom_mul_eq_apSumOffset (f := f) (d := d) (m := m) (n := n)).symm
    simpa [hsum] using hn
  · intro h
    refine (iff_forall_exists_natAbs_apSumOffset_gt (f := f) (d := d) (m := m)).2 ?_
    intro B
    rcases h B with ⟨n, hn⟩
    refine ⟨n, ?_⟩
    have hsum : apSumOffset f d m n = apSumFrom f (m * d) d n := by
      simpa using (apSumFrom_mul_eq_apSumOffset (f := f) (d := d) (m := m) (n := n)).symm
    -- Rewrite the tail nucleus back to the bundled offset nucleus.
    simpa [hsum.symm] using hn

/-- Variant of `iff_forall_exists_natAbs_apSumFrom_mul_gt` with the inequality written as
`Int.natAbs ... > B`.
-/
theorem iff_forall_exists_natAbs_apSumFrom_mul_gt' (f : ℕ → ℤ) (d m : ℕ) :
    UnboundedDiscOffset f d m ↔
      (∀ B : ℕ, ∃ n : ℕ, Int.natAbs (apSumFrom f (m * d) d n) > B) := by
  simpa [gt_iff_lt] using
    (iff_forall_exists_natAbs_apSumFrom_mul_gt (f := f) (d := d) (m := m))

/-- Witness-positivity: in the tail-nucleus witness form
`∀ B, ∃ n, Int.natAbs (apSumFrom f (m*d) d n) > B`,
any witness length `n` is automatically positive.

Reason: `apSumFrom f (m*d) d 0 = 0`.
-/
theorem forall_exists_natAbs_apSumFrom_mul_gt_witness_pos {f : ℕ → ℤ} {d m : ℕ}
    (hunb : UnboundedDiscOffset f d m) :
    ∀ B : ℕ, ∃ n : ℕ, n > 0 ∧ Int.natAbs (apSumFrom f (m * d) d n) > B := by
  intro B
  rcases (iff_forall_exists_natAbs_apSumFrom_mul_gt' (f := f) (d := d) (m := m)).1 hunb B with
    ⟨n, hn⟩
  have hn0 : n ≠ 0 := by
    intro h0
    subst h0
    have hzero : Int.natAbs (apSumFrom f (m * d) d 0) = 0 := by
      simp
    have hn0gt := hn
    rw [hzero] at hn0gt
    have hlt : B < 0 := (gt_iff_lt).1 hn0gt
    exact (Nat.not_lt_zero B) hlt
  exact ⟨n, Nat.pos_of_ne_zero hn0, hn⟩

/-- Negation-normal form: unbounded offset discrepancy means there is no uniform bound on the
affine-tail nuclei `Int.natAbs (apSumFrom f (m*d) d n)`.

This is the tail-nucleus analogue of `iff_not_exists_forall_natAbs_apSumOffset_le`.
-/
theorem iff_not_exists_forall_natAbs_apSumFrom_mul_le (f : ℕ → ℤ) (d m : ℕ) :
    UnboundedDiscOffset f d m ↔
      (¬ ∃ B : ℕ, ∀ n : ℕ, Int.natAbs (apSumFrom f (m * d) d n) ≤ B) := by
  classical
  constructor
  · intro hunb h
    rcases h with ⟨B, hB⟩
    rcases (iff_forall_exists_natAbs_apSumFrom_mul_gt' (f := f) (d := d) (m := m)).1 hunb B with
      ⟨n, hn⟩
    exact (not_lt_of_ge (hB n)) hn
  · intro hnb
    refine (iff_forall_exists_natAbs_apSumFrom_mul_gt' (f := f) (d := d) (m := m)).2 ?_
    intro B
    by_contra h
    have hB : ∀ n : ℕ, Int.natAbs (apSumFrom f (m * d) d n) ≤ B := by
      intro n
      exact le_of_not_gt (by
        intro hgt
        exact h ⟨n, hgt⟩)
    exact hnb ⟨B, hB⟩

/-- Negation-normal form: unbounded offset discrepancy means there is no uniform bound on the
bundled offset nuclei `Int.natAbs (apSumOffset f d m n)`.

This is often the most convenient form for proofs by contradiction.
-/
theorem iff_not_exists_forall_natAbs_apSumOffset_le (f : ℕ → ℤ) (d m : ℕ) :
    UnboundedDiscOffset f d m ↔
      (¬ ∃ B : ℕ, ∀ n : ℕ, Int.natAbs (apSumOffset f d m n) ≤ B) := by
  classical
  constructor
  · intro hunb h
    rcases h with ⟨B, hB⟩
    rcases hunb B with ⟨n, hn⟩
    have hn' : B < Int.natAbs (apSumOffset f d m n) := by
      -- Avoid simp loops: `discOffset` is definitional.
      have hn' := hn
      unfold discOffset at hn'
      exact hn'
    exact (not_lt_of_ge (hB n)) hn'
  · intro hnb B
    by_contra h
    -- If there is no witness beating B, then B is a uniform bound.
    have hB : ∀ n : ℕ, Int.natAbs (apSumOffset f d m n) ≤ B := by
      intro n
      have hnot : ¬ B < discOffset f d m n := by
        intro hlt
        exact h ⟨n, hlt⟩
      have hle : discOffset f d m n ≤ B := by
        exact le_of_not_gt (by
          intro hgt
          exact hnot (by simpa [gt_iff_lt] using hgt))
      -- Avoid simp loops: `discOffset` is definitional.
      have hle' := hle
      unfold discOffset at hle'
      exact hle'
    exact hnb ⟨B, hB⟩

/-- Paper-notation normal form: unbounded offset discrepancy means there is no uniform bound on the
shifted progression sums
`∑ i ∈ Icc (m+1) (m+n), f (i*d)`.

Negation-normal form:
`¬ ∃ B, ∀ n, Int.natAbs ((Icc (m+1) (m+n)).sum (fun i => f (i*d))) ≤ B`.

This is `iff_not_exists_forall_natAbs_apSumOffset_le` rewritten using
`natAbs_apSumOffset_eq_natAbs_sum_Icc`.
-/
theorem iff_not_exists_forall_natAbs_sum_Icc_offset_le (f : ℕ → ℤ) (d m : ℕ) :
    UnboundedDiscOffset f d m ↔
      (¬ ∃ B : ℕ,
        ∀ n : ℕ,
          Int.natAbs ((Finset.Icc (m + 1) (m + n)).sum (fun i => f (i * d))) ≤ B) := by
  have hiff :
      (∃ B : ℕ, ∀ n : ℕ, Int.natAbs (apSumOffset f d m n) ≤ B) ↔
        (∃ B : ℕ,
          ∀ n : ℕ,
            Int.natAbs ((Finset.Icc (m + 1) (m + n)).sum (fun i => f (i * d))) ≤ B) := by
    constructor
    · rintro ⟨B, hB⟩
      refine ⟨B, ?_⟩
      intro n
      simpa [natAbs_apSumOffset_eq_natAbs_sum_Icc (f := f) (d := d) (m := m) (n := n)] using hB n
    · rintro ⟨B, hB⟩
      refine ⟨B, ?_⟩
      intro n
      simpa [natAbs_apSumOffset_eq_natAbs_sum_Icc (f := f) (d := d) (m := m) (n := n)] using hB n

  exact
    (iff_not_exists_forall_natAbs_apSumOffset_le (f := f) (d := d) (m := m)).trans
      (not_congr hiff)

end UnboundedDiscOffset

/-- Normal form: unbounded offset discrepancy means there is no uniform `discOffset` bound.

Negation-normal form:
`¬ ∃ B, ∀ n, discOffset f d m n ≤ B`.

This is the definitional `discOffset` rewrite of
`UnboundedDiscOffset.iff_not_exists_forall_natAbs_apSumOffset_le`.
-/
theorem unboundedDiscOffset_iff_not_exists_forall_discOffset_le (f : ℕ → ℤ) (d m : ℕ) :
    UnboundedDiscOffset f d m ↔ (¬ ∃ B : ℕ, ∀ n : ℕ, discOffset f d m n ≤ B) := by
  -- Avoid simp loops: `discOffset` is definitional.
  simpa [discOffset, -natAbs_apSumOffset_eq_discOffset] using
    (UnboundedDiscOffset.iff_not_exists_forall_natAbs_apSumOffset_le (f := f) (d := d) (m := m))

/-- Preferred naming for the core lemma
`MoltResearch.not_exists_boundedDiscOffset_iff_forall_exists_discOffset_lt`.

The witnesses have the form `B < discOffset ...`, so we use the suffix `_gt` (“greater than B”).
-/
theorem not_exists_boundedDiscOffset_iff_forall_exists_discOffset_gt (f : ℕ → ℤ) (d m : ℕ) :
    (¬ ∃ B : ℕ, BoundedDiscOffset f d m B) ↔ ∀ B : ℕ, ∃ n : ℕ, B < discOffset f d m n := by
  simpa using
    (MoltResearch.not_exists_boundedDiscOffset_iff_forall_exists_discOffset_lt (f := f) (d := d)
      (m := m))

/-- Inequality-direction variant of `not_exists_boundedDiscOffset_iff_forall_exists_discOffset_gt`,
written as `discOffset ... > B`.

Many consumers prefer this normal form so they can `simp [gt_iff_lt]` at the call site.
-/
theorem not_exists_boundedDiscOffset_iff_forall_exists_discOffset_gt' (f : ℕ → ℤ) (d m : ℕ) :
    (¬ ∃ B : ℕ, BoundedDiscOffset f d m B) ↔ (∀ B : ℕ, ∃ n : ℕ, discOffset f d m n > B) := by
  simpa [gt_iff_lt] using
    (not_exists_boundedDiscOffset_iff_forall_exists_discOffset_gt (f := f) (d := d) (m := m))

/-- Bridge: the witness form `UnboundedDiscOffset` is equivalent to the negation-normal-form boundedness
statement `¬ ∃ B, BoundedDiscOffset f d m B`.

This lets later stages switch to a stable boundedness predicate without unfolding `discOffset`.
-/
theorem unboundedDiscOffset_iff_not_exists_boundedDiscOffset (f : ℕ → ℤ) (d m : ℕ) :
    UnboundedDiscOffset f d m ↔ ¬ ∃ B : ℕ, BoundedDiscOffset f d m B := by
  simpa [UnboundedDiscOffset] using
    (not_exists_boundedDiscOffset_iff_forall_exists_discOffset_gt (f := f) (d := d) (m := m)).symm

/-- Monotonicity: a `discOffset` bound can be weakened to any larger bound. -/
theorem boundedDiscOffset_mono {f : ℕ → ℤ} {d m B B' : ℕ}
    (h : BoundedDiscOffset f d m B) (hBB' : B ≤ B') : BoundedDiscOffset f d m B' := by
  intro n
  exact le_trans (h n) hBB'

/-!
### Bridges to the verified along-`d` predicates in `MoltResearch.Discrepancy`

Track C uses bespoke stage-record interfaces under `MoltResearch.Tao2015`, but it is convenient
to interoperate with the verified Track B “along-`d`” normal forms.
-/

/-- Bridge: Track C `HasDiscrepancyAtLeastAlong` agrees with the core predicate
`MoltResearch.HasDiscrepancyAtLeastAlong`. -/
theorem hasDiscrepancyAtLeastAlong_iff_core (g : ℕ → ℤ) (d C : ℕ) :
    HasDiscrepancyAtLeastAlong g d C ↔ MoltResearch.HasDiscrepancyAtLeastAlong g d C := by
  unfold HasDiscrepancyAtLeastAlong MoltResearch.HasDiscrepancyAtLeastAlong
  constructor <;> rintro ⟨n, hn⟩ <;> refine ⟨n, ?_⟩ <;> simpa [gt_iff_lt] using hn

/-- Bridge: Track C `UnboundedDiscrepancyAlong` agrees with the core predicate
`MoltResearch.UnboundedDiscrepancyAlong`. -/
theorem unboundedDiscrepancyAlong_iff_core (g : ℕ → ℤ) (d : ℕ) :
    UnboundedDiscrepancyAlong g d ↔ MoltResearch.UnboundedDiscrepancyAlong g d := by
  unfold UnboundedDiscrepancyAlong MoltResearch.UnboundedDiscrepancyAlong MoltResearch.HasDiscrepancyAtLeastAlong
  constructor
  · intro hunb C
    rcases hunb C with ⟨n, hn⟩
    exact ⟨n, by simpa [gt_iff_lt] using hn⟩
  · intro hunb B
    rcases hunb B with ⟨n, hn⟩
    exact ⟨n, by simpa [gt_iff_lt] using hn⟩

namespace UnboundedDiscrepancyAlong

/-- Classical equivalence: unboundedness along `d` is the negation of boundedness along `d`.

This is just `Tao2015.unboundedDiscrepancyAlong_iff_not_boundedDiscrepancyAlong`, restated in the
namespaced form `UnboundedDiscrepancyAlong.iff_not_boundedDiscrepancyAlong`.
-/
theorem iff_not_boundedDiscrepancyAlong (g : ℕ → ℤ) (d : ℕ) :
    UnboundedDiscrepancyAlong g d ↔ ¬ BoundedDiscrepancyAlong g d := by
  simpa using (Tao2015.unboundedDiscrepancyAlong_iff_not_boundedDiscrepancyAlong (g := g) (d := d))

/-- Nucleus normal form: unboundedness along `d` means there is no uniform bound on
`Int.natAbs (apSum g d n)`.

This is `iff_not_boundedDiscrepancyAlong` composed with
`boundedDiscrepancyAlong_iff_exists_forall_natAbs_apSum_le`.
-/
theorem iff_not_exists_forall_natAbs_apSum_le (g : ℕ → ℤ) (d : ℕ) :
    UnboundedDiscrepancyAlong g d ↔ ¬ ∃ B : ℕ, ∀ n : ℕ, Int.natAbs (apSum g d n) ≤ B := by
  simpa using
    (iff_not_boundedDiscrepancyAlong (g := g) (d := d)).trans
      (not_congr (boundedDiscrepancyAlong_iff_exists_forall_natAbs_apSum_le (g := g) (d := d)))

end UnboundedDiscrepancyAlong

namespace HasDiscrepancyAtLeastAlong

/-- `∀ C, HasDiscrepancyAtLeastAlong g d C` is just `UnboundedDiscrepancyAlong g d`. -/
theorem forall_hasDiscrepancyAtLeastAlong_iff_unboundedDiscrepancyAlong (g : ℕ → ℤ) (d : ℕ) :
    (∀ C : ℕ, HasDiscrepancyAtLeastAlong g d C) ↔ UnboundedDiscrepancyAlong g d := by
  constructor
  · intro h B
    exact h B
  · intro hunb C
    exact hunb C

/-- Witness-positivity: any witness for `HasDiscrepancyAtLeastAlong g d C` must have `n > 0`,
since `discrepancy g d 0 = 0`.

This is a tiny convenience lemma used by later stages to avoid splitting on the `n = 0` case.
-/
theorem exists_witness_pos {g : ℕ → ℤ} {d C : ℕ} (h : HasDiscrepancyAtLeastAlong g d C) :
    ∃ n : ℕ, n > 0 ∧ C < discrepancy g d n := by
  rcases h with ⟨n, hn⟩
  have hn0 : n ≠ 0 := by
    intro h0
    subst h0
    simp [discrepancy_zero] at hn
  exact ⟨n, Nat.pos_of_ne_zero hn0, hn⟩

end HasDiscrepancyAtLeastAlong

/-!
## Global contexts (boundedness data)

These are small records bundling bounds in a consumer-friendly way.
They are intentionally *weak*: later stages can strengthen/replace them.
-/

/-- A global boundedness context for `f`, extracted from `BoundedDiscrepancy f`. -/
structure Context (f : ℕ → ℤ) : Type where
  /-- A global bound. -/
  B : ℕ
  /-- Bound on homogeneous discrepancy (`discrepancy = natAbs(apSum)`). -/
  bound_discrepancy : ∀ d n : ℕ, d > 0 → discrepancy f d n ≤ B
  /-- A convenient derived bound for offset discrepancy families. -/
  bound_discOffset_two_mul : ∀ d m n : ℕ, d > 0 → discOffset f d m n ≤ 2 * B

namespace Context

/-- Build a `Context` from `BoundedDiscrepancy`.

Note: `BoundedDiscrepancy f` lives in `Prop`, while `Context f` is a `Type`, so we must use
classical choice rather than pattern matching on the existential witness.
-/
noncomputable def ofBoundedDiscrepancy (f : ℕ → ℤ) (hb : BoundedDiscrepancy f) : Context f := by
  classical
  let B : ℕ := Classical.choose hb
  have hB : ∀ d n : ℕ, d > 0 → Int.natAbs (apSum f d n) ≤ B := Classical.choose_spec hb
  refine
    { B := B
      bound_discrepancy := ?_
      bound_discOffset_two_mul := ?_ }
  · intro d n hd
    -- `discrepancy` is definitionally `Int.natAbs (apSum ...)`.
    change Int.natAbs (apSum f d n) ≤ B
    exact hB d n hd
  · intro d m n hd
    -- Offset sum is a difference of two prefix sums; use triangle inequality + the global bound.
    have hEq : apSum f d (m + n) + (- apSum f d m) = apSumOffset f d m n := by
      calc
        apSum f d (m + n) + (- apSum f d m)
            = apSum f d (m + n) - apSum f d m := by
                simp [sub_eq_add_neg]
        _ = apSumOffset f d m n :=
          (MoltResearch.apSumOffset_eq_sub (f := f) (d := d) (m := m) (n := n)).symm

    have htri :
        Int.natAbs (apSumOffset f d m n) ≤
          Int.natAbs (apSum f d (m + n)) + Int.natAbs (apSum f d m) := by
      simpa [hEq, Int.natAbs_neg] using
        (Int.natAbs_add_le (apSum f d (m + n)) (- apSum f d m))

    have hsum :
        Int.natAbs (apSum f d (m + n)) + Int.natAbs (apSum f d m) ≤ B + B :=
      Nat.add_le_add (hB d (m + n) hd) (hB d m hd)

    have hfinal : Int.natAbs (apSumOffset f d m n) ≤ B + B :=
      le_trans htri hsum

    have : discOffset f d m n ≤ B + B := by
      change Int.natAbs (apSumOffset f d m n) ≤ B + B
      exact hfinal

    simpa [two_mul] using this

/-- Convenience normal form: the global `discOffset` bound bundled in `Context` is equivalently a
bound on the bundled offset nucleus `Int.natAbs (apSumOffset ...)`.

This prevents consumers from having to unfold `discOffset` at each call site.
-/
theorem bound_natAbs_apSumOffset_two_mul {f : ℕ → ℤ} (ctx : Context f) (d m n : ℕ) (hd : d > 0) :
    Int.natAbs (apSumOffset f d m n) ≤ 2 * ctx.B := by
  -- `discOffset` is definitionally `Int.natAbs (apSumOffset ...)`, so this is exactly the stored bound.
  exact ctx.bound_discOffset_two_mul (d := d) (m := m) (n := n) hd

/-- Package the stored `discOffset` bound as a `BoundedDiscOffset` witness. -/
theorem boundedDiscOffset_two_mul {f : ℕ → ℤ} (ctx : Context f) (d m : ℕ) (hd : d > 0) :
    BoundedDiscOffset f d m (2 * ctx.B) := by
  intro n
  simpa using ctx.bound_discOffset_two_mul (d := d) (m := m) (n := n) hd

end Context

/-- Fixed-step analogue of `Context`: a bound on `discrepancy g d n` for all `n`. -/
structure ContextAlong (g : ℕ → ℤ) (d : ℕ) : Type where
  B : ℕ
  bound_discrepancy : ∀ n : ℕ, discrepancy g d n ≤ B

namespace ContextAlong

/-- Build a `ContextAlong` from `BoundedDiscrepancyAlong`.

As with `Context.ofBoundedDiscrepancy`, we use classical choice to extract the witness.
-/
noncomputable def ofBoundedDiscrepancyAlong {g : ℕ → ℤ} {d : ℕ} (hb : BoundedDiscrepancyAlong g d) :
    ContextAlong g d := by
  classical
  let B : ℕ := Classical.choose hb
  have hB : ∀ n : ℕ, discrepancy g d n ≤ B := Classical.choose_spec hb
  exact ⟨B, hB⟩

/-- Turn a `ContextAlong` back into `BoundedDiscrepancyAlong`. -/
theorem toBoundedDiscrepancyAlong {g : ℕ → ℤ} {d : ℕ} (ctx : ContextAlong g d) :
    BoundedDiscrepancyAlong g d := by
  exact ⟨ctx.B, ctx.bound_discrepancy⟩

/-- Normal form: the discrepancy bound stored in `ContextAlong` is equivalently a bound on the
fixed-step nucleus `Int.natAbs (apSum g d n)`.

This prevents consumers from having to unfold `discrepancy` at each call site.
-/
theorem bound_natAbs_apSum {g : ℕ → ℤ} {d : ℕ} (ctx : ContextAlong g d) (n : ℕ) :
    Int.natAbs (apSum g d n) ≤ ctx.B := by
  -- `discrepancy g d n` is definitionally `Int.natAbs (apSum g d n)`.
  change discrepancy g d n ≤ ctx.B
  exact ctx.bound_discrepancy n

end ContextAlong

/-- If some offset discrepancy family is unbounded, then `f` cannot have globally bounded discrepancy.

This is the global (non–Stage-1-specific) contrapositive used by later stages: global bounded
discrepancy implies a uniform bound on every `discOffset f d m`, so unboundedness of any one such
family yields a contradiction.
-/
theorem not_boundedDiscrepancy_of_forall_exists_discOffset_gt (f : ℕ → ℤ) {d m : ℕ} (hd : d > 0)
    (hunb : ∀ B : ℕ, ∃ n : ℕ, B < discOffset f d m n) :
    ¬ BoundedDiscrepancy f := by
  intro hb
  -- Turn global boundedness into a reusable `Context`, then contradict the unbounded witness.
  let ctx : Context f := Context.ofBoundedDiscrepancy (f := f) hb
  have hbound : ∀ n : ℕ, discOffset f d m n ≤ 2 * ctx.B := by
    intro n
    simpa using (ctx.bound_discOffset_two_mul (f := f) (d := d) (m := m) (n := n) hd)
  rcases hunb (2 * ctx.B) with ⟨n, hn⟩
  exact (not_lt_of_ge (hbound n)) hn

/-- Variant of `not_boundedDiscrepancy_of_forall_exists_discOffset_gt` with the witness inequality
written as `discOffset ... > B`.

Many consumers prefer this normal form so they can `simp [gt_iff_lt]` at the call site.
-/
theorem not_boundedDiscrepancy_of_forall_exists_discOffset_gt' (f : ℕ → ℤ) {d m : ℕ} (hd : d > 0)
    (hunb : ∀ B : ℕ, ∃ n : ℕ, discOffset f d m n > B) :
    ¬ BoundedDiscrepancy f := by
  refine not_boundedDiscrepancy_of_forall_exists_discOffset_gt (f := f) (d := d) (m := m) hd ?_
  intro B
  rcases hunb B with ⟨n, hn⟩
  exact ⟨n, (gt_iff_lt).1 hn⟩

/-!
## Stage 1: shift reduction output

Stage 1 packages a derived sign sequence `g` (typically a shift of `f`), together with a fixed
step size `d` and an offset parameter `m`, plus *transport contracts* between discrepancy
statements about `g` and offset discrepancy statements about `f`.

This is deliberately an IO-style record: downstream stages should consume the record rather than
re-proving ad-hoc rewrites.
-/

structure ReductionOutput (f : ℕ → ℤ) : Type where
  /-- Fixed step size for the reduced locus. -/
  d : ℕ
  /-- The step size is positive.

  Most discrepancy statements (including `BoundedDiscrepancy`) only quantify over `d > 0`.
  We store this here so later stages can use it without threading it separately.
  -/
  hd : d > 0
  /-- Offset parameter bundling the tail `m*d`. -/
  m : ℕ
  /-- Reduced sign sequence. -/
  g : ℕ → ℤ
  /-- Proof that `g` is a sign sequence. -/
  hg : IsSignSequence g
  /-- Defining equation: `g k = f (k + m*d)`.

  We keep this explicit because it is frequently used for rewriting.
  -/
  g_eq : ∀ k : ℕ, g k = f (k + m * d)
  /-- Transfer contract: a uniform bound on `discOffset f d m` bounds `discrepancy g d`. -/
  contract_discrepancy_le :
    ∀ B : ℕ, (∀ n : ℕ, discOffset f d m n ≤ B) → ∀ n : ℕ, discrepancy g d n ≤ B

namespace ReductionOutput

variable {f : ℕ → ℤ}

/-- Canonical Stage-1 reduction: shift `f` by `m*d`.

This is the “pure index gymnastics” step: it defines
`g k := f (k + m*d)`.

The transport contract `contract_discrepancy_le` is discharged by rewriting
`discrepancy (fun k => f (k + m*d)) d` into the bundled offset form `discOffset f d m`.
-/
def ofShift (f : ℕ → ℤ) (hf : IsSignSequence f) (d m : ℕ) (hd : d > 0) : ReductionOutput f := by
  classical
  refine
    { d := d
      hd := hd
      m := m
      g := fun k => f (k + m * d)
      hg := ?_
      g_eq := ?_
      contract_discrepancy_le := ?_ }
  · intro k
    simpa using hf (k + m * d)
  · intro k
    rfl
  · intro B hB n
    -- Normalize the reduced discrepancy to the bundled offset discrepancy wrapper.
    have hrewrite :
        discrepancy (fun k => f (k + m * d)) d n = discOffset f d m n := by
      -- `discrepancy_shift_mul_simp` is the standard normal form for shifts by `m*d`.
      exact discrepancy_shift_mul_simp (f := f) (m := m) (d := d) (n := n)
    -- Now discharge the bound using the supplied uniform `discOffset` bound.
    simpa [hrewrite] using hB n

/-- Consumer-facing rewrite: discrepancy of the reduced sequence equals bundled offset discrepancy.

This is the key normal-form bridge used by later stages.
-/
theorem discrepancy_eq_discOffset_via_contract (out : ReductionOutput f) (n : ℕ) :
    discrepancy out.g out.d n = discOffset f out.d out.m n := by
  -- `out.g_eq` identifies `out.g` with the canonical shift `fun k ↦ f (k + m*d)`.
  have hgfun : out.g = fun k => f (k + out.m * out.d) := by
    funext k
    simp [out.g_eq]
  -- Now normalize discrepancy of a shift by `m*d`.
  simp [hgfun, discrepancy_shift_mul_simp (f := f) (m := out.m) (d := out.d) (n := n)]

/-- Convenience: pointwise discrepancy bounds for the reduced sequence are exactly pointwise bounds
on the bundled offset family. -/
theorem discrepancy_le_iff_discOffset_le (out : ReductionOutput f) (n B : ℕ) :
    discrepancy out.g out.d n ≤ B ↔ discOffset f out.d out.m n ≤ B := by
  simp [out.discrepancy_eq_discOffset_via_contract (f := f) (n := n)]

/-- Convenience: uniform discrepancy bounds for the reduced sequence are exactly uniform bounds on
the bundled offset family. -/
theorem forall_discrepancy_le_iff_forall_discOffset_le (out : ReductionOutput f) (B : ℕ) :
    (∀ n : ℕ, discrepancy out.g out.d n ≤ B) ↔ (∀ n : ℕ, discOffset f out.d out.m n ≤ B) := by
  constructor
  · intro h n
    exact (out.discrepancy_le_iff_discOffset_le (f := f) (n := n) (B := B)).1 (h n)
  · intro h n
    exact (out.discrepancy_le_iff_discOffset_le (f := f) (n := n) (B := B)).2 (h n)

/-- Bounded discrepancy along the reduced step is equivalent to a uniform bound on the bundled offset
discrepancy family.

This is a tiny packaging lemma: it lets consumers switch between the fixed-step normal form
(`discrepancy out.g out.d`) and the bundled offset normal form (`discOffset f out.d out.m`).
-/
theorem boundedDiscrepancyAlong_iff_exists_forall_discOffset_le (out : ReductionOutput f) :
    BoundedDiscrepancyAlong out.g out.d ↔
      ∃ B : ℕ, ∀ n : ℕ, discOffset f out.d out.m n ≤ B := by
  unfold BoundedDiscrepancyAlong
  constructor
  · rintro ⟨B, hB⟩
    refine ⟨B, (out.forall_discrepancy_le_iff_forall_discOffset_le (f := f) B).1 hB⟩
  · rintro ⟨B, hB⟩
    refine ⟨B, (out.forall_discrepancy_le_iff_forall_discOffset_le (f := f) B).2 hB⟩

/-- Packaged form of `boundedDiscrepancyAlong_iff_exists_forall_discOffset_le` using the verified
predicate `BoundedDiscOffset`.

This keeps downstream code from having to remember the exact quantifier normal form of
`BoundedDiscOffset`.
-/
theorem boundedDiscrepancyAlong_iff_exists_boundedDiscOffset (out : ReductionOutput f) :
    BoundedDiscrepancyAlong out.g out.d ↔ ∃ B : ℕ, BoundedDiscOffset f out.d out.m B := by
  simpa [BoundedDiscOffset] using out.boundedDiscrepancyAlong_iff_exists_forall_discOffset_le (f := f)

/-- Stage-1 witness transport: reduced discrepancy-at-least is an affine-tail witness for `f`.

The affine nucleus is `apSumFrom f (m*d) d n`.
-/
theorem hasDiscrepancyAtLeastAlong_iff_exists_natAbs_apSumFrom_mul_gt (out : ReductionOutput f)
    (C : ℕ) :
    HasDiscrepancyAtLeastAlong out.g out.d C ↔
      ∃ n : ℕ, Int.natAbs (apSumFrom f (out.m * out.d) out.d n) > C := by
  unfold HasDiscrepancyAtLeastAlong
  constructor
  · rintro ⟨n, hn⟩
    refine ⟨n, ?_⟩
    have hn' : C < discOffset f out.d out.m n := by
      simpa [discrepancy_eq_discOffset_via_contract (f := f) (out := out) (n := n)] using hn
    have hnOffset : C < Int.natAbs (apSumOffset f out.d out.m n) := by
      have hnOffset := hn'
      unfold discOffset at hnOffset
      exact hnOffset
    have hsum : apSumFrom f (out.m * out.d) out.d n = apSumOffset f out.d out.m n := by
      simpa using (apSumFrom_mul_eq_apSumOffset (f := f) (d := out.d) (m := out.m) (n := n))
    have hnFrom : C < Int.natAbs (apSumFrom f (out.m * out.d) out.d n) := by
      simpa [hsum] using hnOffset
    simpa [gt_iff_lt] using hnFrom

  · rintro ⟨n, hn⟩
    refine ⟨n, ?_⟩
    have hnFrom : C < Int.natAbs (apSumFrom f (out.m * out.d) out.d n) := by
      simpa [gt_iff_lt] using hn
    have hsum : apSumFrom f (out.m * out.d) out.d n = apSumOffset f out.d out.m n := by
      simpa using (apSumFrom_mul_eq_apSumOffset (f := f) (d := out.d) (m := out.m) (n := n))
    have hnOffset : C < Int.natAbs (apSumOffset f out.d out.m n) := by
      simpa [hsum] using hnFrom
    have hnDiscOffset : C < discOffset f out.d out.m n := by
      change C < Int.natAbs (apSumOffset f out.d out.m n)
      exact hnOffset
    simpa [discrepancy_eq_discOffset_via_contract (f := f) (out := out) (n := n)] using hnDiscOffset

/-- Stage-1 transport: unbounded fixed-step discrepancy for the reduced sequence is equivalent to
arbitrarily large affine-tail witnesses for `f`.

This is the `∀ C` version of `hasDiscrepancyAtLeastAlong_iff_exists_natAbs_apSumFrom_mul_gt`.
-/
theorem unboundedDiscrepancyAlong_iff_forall_exists_natAbs_apSumFrom_mul_gt (out : ReductionOutput f) :
    UnboundedDiscrepancyAlong out.g out.d ↔
      ∀ C : ℕ, ∃ n : ℕ, Int.natAbs (apSumFrom f (out.m * out.d) out.d n) > C := by
  constructor
  · intro hunb C
    exact
      (out.hasDiscrepancyAtLeastAlong_iff_exists_natAbs_apSumFrom_mul_gt (f := f) (C := C)).1
        (hunb C)
  · intro h B
    exact
      (out.hasDiscrepancyAtLeastAlong_iff_exists_natAbs_apSumFrom_mul_gt (f := f) (C := B)).2
        (h B)

/-- Stage-1 transport: the family statement `∀ C, HasDiscrepancyAtLeastAlong out.g out.d C`
is equivalent to explicit affine-tail nucleus witnesses for `f`.

This is a convenience wrapper combining
`HasDiscrepancyAtLeastAlong.forall_hasDiscrepancyAtLeastAlong_iff_unboundedDiscrepancyAlong`
with `unboundedDiscrepancyAlong_iff_forall_exists_natAbs_apSumFrom_mul_gt`.
-/
theorem forall_hasDiscrepancyAtLeastAlong_iff_forall_exists_natAbs_apSumFrom_mul_gt
    (out : ReductionOutput f) :
    (∀ C : ℕ, HasDiscrepancyAtLeastAlong out.g out.d C) ↔
      (∀ C : ℕ, ∃ n : ℕ, Int.natAbs (apSumFrom f (out.m * out.d) out.d n) > C) := by
  constructor
  · intro h
    have hunb : UnboundedDiscrepancyAlong out.g out.d :=
      (HasDiscrepancyAtLeastAlong.forall_hasDiscrepancyAtLeastAlong_iff_unboundedDiscrepancyAlong
        (g := out.g) (d := out.d)).1 h
    exact
      (out.unboundedDiscrepancyAlong_iff_forall_exists_natAbs_apSumFrom_mul_gt (f := f)).1 hunb
  · intro h
    have hunb : UnboundedDiscrepancyAlong out.g out.d :=
      (out.unboundedDiscrepancyAlong_iff_forall_exists_natAbs_apSumFrom_mul_gt (f := f)).2 h
    exact
      (HasDiscrepancyAtLeastAlong.forall_hasDiscrepancyAtLeastAlong_iff_unboundedDiscrepancyAlong
        (g := out.g) (d := out.d)).2 hunb

/-- Unboundedness of reduced discrepancy is equivalent to unboundedness of the bundled offset family.

The suffix `_lt` is legacy: the witness is `B < ...` (i.e. “greater than B”).
-/
@[deprecated "Use `unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt` (witnesses are of the form `B < discOffset ...`)." (since := "2026-03-24")]
theorem unboundedDiscrepancyAlong_iff_forall_exists_discOffset_lt (out : ReductionOutput f) :
    UnboundedDiscrepancyAlong out.g out.d ↔ (∀ B : ℕ, ∃ n : ℕ, B < discOffset f out.d out.m n) := by
  constructor
  · intro hunb B
    rcases hunb B with ⟨n, hn⟩
    refine ⟨n, ?_⟩
    simpa [discrepancy_eq_discOffset_via_contract (out := out) (n := n)] using hn
  · intro hunb B
    rcases hunb B with ⟨n, hn⟩
    refine ⟨n, ?_⟩
    simpa [discrepancy_eq_discOffset_via_contract (out := out) (n := n)] using hn

/-- Preferred naming for `unboundedDiscrepancyAlong_iff_forall_exists_discOffset_lt`.

The witnesses have the form `B < discOffset ...`, so we use the suffix `_gt` (“greater than B”).
-/
theorem unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt (out : ReductionOutput f) :
    UnboundedDiscrepancyAlong out.g out.d ↔ (∀ B : ℕ, ∃ n : ℕ, B < discOffset f out.d out.m n) := by
  constructor
  · intro hunb B
    rcases hunb B with ⟨n, hn⟩
    refine ⟨n, ?_⟩
    simpa [discrepancy_eq_discOffset_via_contract (out := out) (n := n)] using hn
  · intro hunb B
    rcases hunb B with ⟨n, hn⟩
    refine ⟨n, ?_⟩
    simpa [discrepancy_eq_discOffset_via_contract (out := out) (n := n)] using hn

/-- Inequality-direction variant of `unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt`,
written as `discOffset ... > B`.

Many consumers prefer this normal form so they can `simp [gt_iff_lt]` at the call site.
-/
theorem unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt' (out : ReductionOutput f) :
    UnboundedDiscrepancyAlong out.g out.d ↔
      (∀ B : ℕ, ∃ n : ℕ, discOffset f out.d out.m n > B) := by
  simpa [gt_iff_lt] using
    (unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt (f := f) (out := out))

/-- Packaged predicate form: reduced-step unbounded discrepancy is equivalent to unboundedness of the
bundled offset discrepancy family for `f`.
-/
theorem unboundedDiscrepancyAlong_iff_unboundedDiscOffset (out : ReductionOutput f) :
    UnboundedDiscrepancyAlong out.g out.d ↔ UnboundedDiscOffset f out.d out.m := by
  simpa [UnboundedDiscOffset] using
    (unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt (f := f) (out := out))

/-- Nucleus-level variant of `unboundedDiscrepancyAlong_iff_forall_exists_discOffset_lt`. -/
@[deprecated "Use `unboundedDiscrepancyAlong_iff_forall_exists_natAbs_apSumOffset_gt` (witnesses are of the form `B < Int.natAbs ...`)." (since := "2026-03-24")]
theorem unboundedDiscrepancyAlong_iff_forall_exists_natAbs_apSumOffset_lt (out : ReductionOutput f) :
    UnboundedDiscrepancyAlong out.g out.d ↔
      (∀ B : ℕ, ∃ n : ℕ, B < Int.natAbs (apSumOffset f out.d out.m n)) := by
  constructor
  · intro hunb
    have hdisc : ∀ B : ℕ, ∃ n : ℕ, B < discOffset f out.d out.m n :=
      (unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt (f := f) (out := out)).1 hunb
    intro B
    rcases hdisc B with ⟨n, hn⟩
    exact ⟨n, hn⟩
  · intro hunb
    refine
      (unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt (f := f) (out := out)).2 ?_
    intro B
    rcases hunb B with ⟨n, hn⟩
    exact ⟨n, hn⟩

/-- Preferred naming for `unboundedDiscrepancyAlong_iff_forall_exists_natAbs_apSumOffset_lt`.

The witnesses have the form `B < Int.natAbs ...`, so we use the suffix `_gt` (“greater than B”).
-/
theorem unboundedDiscrepancyAlong_iff_forall_exists_natAbs_apSumOffset_gt (out : ReductionOutput f) :
    UnboundedDiscrepancyAlong out.g out.d ↔
      (∀ B : ℕ, ∃ n : ℕ, B < Int.natAbs (apSumOffset f out.d out.m n)) := by
  constructor
  · intro hunb
    have hdisc : ∀ B : ℕ, ∃ n : ℕ, B < discOffset f out.d out.m n :=
      (unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt (f := f) (out := out)).1 hunb
    intro B
    rcases hdisc B with ⟨n, hn⟩
    exact ⟨n, hn⟩
  · intro hunb
    refine
      (unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt (f := f) (out := out)).2 ?_
    intro B
    rcases hunb B with ⟨n, hn⟩
    exact ⟨n, hn⟩

/-- If the bundled offset discrepancies are unbounded, then `f` cannot have globally bounded discrepancy. -/
theorem not_boundedDiscrepancy_of_forall_exists_discOffset_gt (out : ReductionOutput f)
    (hunb : ∀ B : ℕ, ∃ n : ℕ, B < discOffset f out.d out.m n) :
    ¬ BoundedDiscrepancy f := by
  exact
    Tao2015.not_boundedDiscrepancy_of_forall_exists_discOffset_gt (f := f) (d := out.d) (m := out.m)
      out.hd hunb

/-- If reduced discrepancy along `out.d` is unbounded, then `f` cannot have globally bounded discrepancy.

This is just `not_boundedDiscrepancy_of_forall_exists_discOffset_gt` composed with the Stage-1
transport equivalence `unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt`.
-/
theorem not_boundedDiscrepancy_of_unboundedDiscrepancyAlong (out : ReductionOutput f)
    (hunb : UnboundedDiscrepancyAlong out.g out.d) :
    ¬ BoundedDiscrepancy f := by
  refine ReductionOutput.not_boundedDiscrepancy_of_forall_exists_discOffset_gt (f := f) (out := out) ?_
  exact (unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt (f := f) (out := out)).1 hunb

end ReductionOutput

/-- If an offset discrepancy family is unbounded (packaged form), then `f` cannot have globally
bounded discrepancy.

This is just `not_boundedDiscrepancy_of_forall_exists_discOffset_gt` with `UnboundedDiscOffset`
unfolded.
-/
theorem not_boundedDiscrepancy_of_unboundedDiscOffset (f : ℕ → ℤ) {d m : ℕ} (hd : d > 0)
    (hunb : UnboundedDiscOffset f d m) :
    ¬ BoundedDiscrepancy f := by
  refine
    Tao2015.not_boundedDiscrepancy_of_forall_exists_discOffset_gt (f := f) (d := d) (m := m) hd ?_
  simpa [UnboundedDiscOffset] using hunb

/-- Variant of `not_boundedDiscrepancy_of_unboundedDiscOffset` with the step-size side condition
written as `1 ≤ d`.

Many later stages prefer `1 ≤ d` to avoid rewriting `d > 0`.
-/
theorem not_boundedDiscrepancy_of_unboundedDiscOffset_one_le (f : ℕ → ℤ) {d m : ℕ} (hd : 1 ≤ d)
    (hunb : UnboundedDiscOffset f d m) :
    ¬ BoundedDiscrepancy f := by
  have hd' : d > 0 := lt_of_lt_of_le Nat.zero_lt_one hd
  exact not_boundedDiscrepancy_of_unboundedDiscOffset (f := f) (d := d) (m := m) hd' hunb

/-- Variant of `not_boundedDiscrepancy_of_unboundedDiscOffset` with the step-size side condition
written as `d ≠ 0`.

This is often the natural hypothesis produced by stage output records.
-/
theorem not_boundedDiscrepancy_of_unboundedDiscOffset_ne_zero (f : ℕ → ℤ) {d m : ℕ} (hd : d ≠ 0)
    (hunb : UnboundedDiscOffset f d m) :
    ¬ BoundedDiscrepancy f := by
  have hd' : d > 0 := Nat.pos_of_ne_zero hd
  exact not_boundedDiscrepancy_of_unboundedDiscOffset (f := f) (d := d) (m := m) hd' hunb

end Tao2015

end MoltResearch
