import MoltResearch.Discrepancy

/-!
# Tao 2015: Erdős discrepancy theorem (Track C skeleton)

This module is **Conjectures-only**: it may contain axiom stubs (and, if needed, `sorry`).

At present, the only non-verified assumption is the Stage-2 axiom in
`Conjectures.C0002_erdos_discrepancy.src.TrackCStage2Proof`.

Hard goal for Track C automation: make

`lake build Conjectures.C0002_erdos_discrepancy.src.ErdosDiscrepancy`

compile cleanly, while providing *typed stage interfaces* for the Tao 2015 proof pipeline.

Design principles:
- Keep the surface small and stable (records + a few normal-form predicates).
- Avoid lemma sprawl in `MoltResearch/` (verified substrate lives elsewhere).
- Prefer explicit stage boundaries (`ReductionOutput`, `Stage2Output`, `Stage3Output`).

Note: The previous version of this file accrued a lot of autogenerated glue and became
non-compiling (duplicate declarations + simp loops). This rewrite restores a minimal,
compiling interface.
-/

namespace MoltResearch

namespace Tao2015

set_option autoImplicit false

/-!
## Fixed-step discrepancy normal forms

These are the Track C “along a fixed step `d`” analogues of the global predicates in
`MoltResearch.Discrepancy.Unbounded`.
-/

/-- `g` has bounded discrepancy along the fixed step `d`. -/
def BoundedDiscrepancyAlong (g : ℕ → ℤ) (d : ℕ) : Prop :=
  ∃ B : ℕ, ∀ n : ℕ, discrepancy g d n ≤ B

/-- `g` has unbounded discrepancy along the fixed step `d` (witness form). -/
def UnboundedDiscrepancyAlong (g : ℕ → ℤ) (d : ℕ) : Prop :=
  ∀ B : ℕ, ∃ n : ℕ, B < discrepancy g d n

/-- `g` has discrepancy at least `C` along the fixed step `d` (witness form). -/
def HasDiscrepancyAtLeastAlong (g : ℕ → ℤ) (d : ℕ) (C : ℕ) : Prop :=
  ∃ n : ℕ, C < discrepancy g d n

/-- Unboundedness of a bundled offset discrepancy family. -/
def UnboundedDiscOffset (f : ℕ → ℤ) (d m : ℕ) : Prop :=
  ∀ B : ℕ, ∃ n : ℕ, B < discOffset f d m n

/-!
### Bridges to the verified along-`d` predicates in `MoltResearch.Discrepancy`

Track C uses bespoke stage-record interfaces under `MoltResearch.Tao2015`, but it is convenient
to interoperate with the verified Track B “along-`d`” normal forms.
-/

/-- Bridge: Track C `HasDiscrepancyAtLeastAlong` agrees with the core predicate
`MoltResearch.HasDiscrepancyAtLeastAlong`. -/
theorem hasDiscrepancyAtLeastAlong_iff_core (g : ℕ → ℤ) (d C : ℕ) :
    HasDiscrepancyAtLeastAlong g d C ↔ MoltResearch.HasDiscrepancyAtLeastAlong g d C := by
  unfold HasDiscrepancyAtLeastAlong MoltResearch.HasDiscrepancyAtLeastAlong
  constructor <;> rintro ⟨n, hn⟩ <;> refine ⟨n, ?_⟩ <;> simpa [gt_iff_lt] using hn

/-- Bridge: Track C `UnboundedDiscrepancyAlong` agrees with the core predicate
`MoltResearch.UnboundedDiscrepancyAlong`. -/
theorem unboundedDiscrepancyAlong_iff_core (g : ℕ → ℤ) (d : ℕ) :
    UnboundedDiscrepancyAlong g d ↔ MoltResearch.UnboundedDiscrepancyAlong g d := by
  unfold UnboundedDiscrepancyAlong MoltResearch.UnboundedDiscrepancyAlong MoltResearch.HasDiscrepancyAtLeastAlong
  constructor
  · intro hunb C
    rcases hunb C with ⟨n, hn⟩
    exact ⟨n, by simpa [gt_iff_lt] using hn⟩
  · intro hunb B
    rcases hunb B with ⟨n, hn⟩
    exact ⟨n, by simpa [gt_iff_lt] using hn⟩

namespace UnboundedDiscrepancyAlong

/-- Classical equivalence: unboundedness along `d` is the negation of boundedness along `d`. -/
theorem iff_not_boundedDiscrepancyAlong (g : ℕ → ℤ) (d : ℕ) :
    UnboundedDiscrepancyAlong g d ↔ ¬ BoundedDiscrepancyAlong g d := by
  classical
  constructor
  · intro hunb hb
    rcases hb with ⟨B, hB⟩
    rcases hunb B with ⟨n, hn⟩
    exact (not_lt_of_ge (hB n)) hn
  · intro hnb
    intro B
    by_contra h
    have hB : ∀ n : ℕ, discrepancy g d n ≤ B := by
      intro n
      refine le_of_not_gt ?_
      intro hgt
      exact h ⟨n, hgt⟩
    exact hnb ⟨B, hB⟩

end UnboundedDiscrepancyAlong

namespace HasDiscrepancyAtLeastAlong

/-- `∀ C, HasDiscrepancyAtLeastAlong g d C` is just `UnboundedDiscrepancyAlong g d`. -/
theorem forall_hasDiscrepancyAtLeastAlong_iff_unboundedDiscrepancyAlong (g : ℕ → ℤ) (d : ℕ) :
    (∀ C : ℕ, HasDiscrepancyAtLeastAlong g d C) ↔ UnboundedDiscrepancyAlong g d := by
  constructor
  · intro h B
    exact h B
  · intro hunb C
    exact hunb C

end HasDiscrepancyAtLeastAlong

/-!
## Global contexts (boundedness data)

These are small records bundling bounds in a consumer-friendly way.
They are intentionally *weak*: later stages can strengthen/replace them.
-/

/-- A global boundedness context for `f`, extracted from `BoundedDiscrepancy f`. -/
structure Context (f : ℕ → ℤ) : Type where
  /-- A global bound. -/
  B : ℕ
  /-- Bound on homogeneous discrepancy (`discrepancy = natAbs(apSum)`). -/
  bound_discrepancy : ∀ d n : ℕ, d > 0 → discrepancy f d n ≤ B
  /-- A convenient derived bound for offset discrepancy families. -/
  bound_discOffset_two_mul : ∀ d m n : ℕ, d > 0 → discOffset f d m n ≤ 2 * B

namespace Context

/-- Build a `Context` from `BoundedDiscrepancy`.

Note: `BoundedDiscrepancy f` lives in `Prop`, while `Context f` is a `Type`, so we must use
classical choice rather than pattern matching on the existential witness.
-/
noncomputable def ofBoundedDiscrepancy (f : ℕ → ℤ) (hb : BoundedDiscrepancy f) : Context f := by
  classical
  let B : ℕ := Classical.choose hb
  have hB : ∀ d n : ℕ, d > 0 → Int.natAbs (apSum f d n) ≤ B := Classical.choose_spec hb
  refine
    { B := B
      bound_discrepancy := ?_
      bound_discOffset_two_mul := ?_ }
  · intro d n hd
    -- `discrepancy` is definitionally `Int.natAbs (apSum ...)`.
    change Int.natAbs (apSum f d n) ≤ B
    exact hB d n hd
  · intro d m n hd
    -- Offset sum is a difference of two prefix sums; use triangle inequality + the global bound.
    have hEq : apSum f d (m + n) + (- apSum f d m) = apSumOffset f d m n := by
      calc
        apSum f d (m + n) + (- apSum f d m)
            = apSum f d (m + n) - apSum f d m := by
                simp [sub_eq_add_neg]
        _ = apSumOffset f d m n :=
          (MoltResearch.apSumOffset_eq_sub (f := f) (d := d) (m := m) (n := n)).symm

    have htri :
        Int.natAbs (apSumOffset f d m n) ≤
          Int.natAbs (apSum f d (m + n)) + Int.natAbs (apSum f d m) := by
      simpa [hEq, Int.natAbs_neg] using
        (Int.natAbs_add_le (apSum f d (m + n)) (- apSum f d m))

    have hsum :
        Int.natAbs (apSum f d (m + n)) + Int.natAbs (apSum f d m) ≤ B + B :=
      Nat.add_le_add (hB d (m + n) hd) (hB d m hd)

    have hfinal : Int.natAbs (apSumOffset f d m n) ≤ B + B :=
      le_trans htri hsum

    have : discOffset f d m n ≤ B + B := by
      change Int.natAbs (apSumOffset f d m n) ≤ B + B
      exact hfinal

    simpa [two_mul] using this

end Context

/-- Fixed-step analogue of `Context`: a bound on `discrepancy g d n` for all `n`. -/
structure ContextAlong (g : ℕ → ℤ) (d : ℕ) : Type where
  B : ℕ
  bound_discrepancy : ∀ n : ℕ, discrepancy g d n ≤ B

namespace ContextAlong

/-- Build a `ContextAlong` from `BoundedDiscrepancyAlong`.

As with `Context.ofBoundedDiscrepancy`, we use classical choice to extract the witness.
-/
noncomputable def ofBoundedDiscrepancyAlong {g : ℕ → ℤ} {d : ℕ} (hb : BoundedDiscrepancyAlong g d) :
    ContextAlong g d := by
  classical
  let B : ℕ := Classical.choose hb
  have hB : ∀ n : ℕ, discrepancy g d n ≤ B := Classical.choose_spec hb
  exact ⟨B, hB⟩

/-- Turn a `ContextAlong` back into `BoundedDiscrepancyAlong`. -/
theorem toBoundedDiscrepancyAlong {g : ℕ → ℤ} {d : ℕ} (ctx : ContextAlong g d) :
    BoundedDiscrepancyAlong g d := by
  exact ⟨ctx.B, ctx.bound_discrepancy⟩

end ContextAlong

/-!
## Stage 1: shift reduction output

Stage 1 packages a derived sign sequence `g` (typically a shift of `f`), together with a fixed
step size `d` and an offset parameter `m`, plus *transport contracts* between discrepancy
statements about `g` and offset discrepancy statements about `f`.

This is deliberately an IO-style record: downstream stages should consume the record rather than
re-proving ad-hoc rewrites.
-/

structure ReductionOutput (f : ℕ → ℤ) : Type where
  /-- Fixed step size for the reduced locus. -/
  d : ℕ
  /-- The step size is positive.

  Most discrepancy statements (including `BoundedDiscrepancy`) only quantify over `d > 0`.
  We store this here so later stages can use it without threading it separately.
  -/
  hd : d > 0
  /-- Offset parameter bundling the tail `m*d`. -/
  m : ℕ
  /-- Reduced sign sequence. -/
  g : ℕ → ℤ
  /-- Proof that `g` is a sign sequence. -/
  hg : IsSignSequence g
  /-- Defining equation: `g k = f (k + m*d)`.

  We keep this explicit because it is frequently used for rewriting.
  -/
  g_eq : ∀ k : ℕ, g k = f (k + m * d)
  /-- Transfer contract: a uniform bound on `discOffset f d m` bounds `discrepancy g d`. -/
  contract_discrepancy_le :
    ∀ B : ℕ, (∀ n : ℕ, discOffset f d m n ≤ B) → ∀ n : ℕ, discrepancy g d n ≤ B

namespace ReductionOutput

variable {f : ℕ → ℤ}

/-- Canonical Stage-1 reduction: shift `f` by `m*d`.

This is the “pure index gymnastics” step: it defines
`g k := f (k + m*d)`.

The transport contract `contract_discrepancy_le` is discharged by rewriting
`discrepancy (fun k => f (k + m*d)) d` into the bundled offset form `discOffset f d m`.
-/
def ofShift (f : ℕ → ℤ) (hf : IsSignSequence f) (d m : ℕ) (hd : d > 0) : ReductionOutput f := by
  classical
  refine
    { d := d
      hd := hd
      m := m
      g := fun k => f (k + m * d)
      hg := ?_
      g_eq := ?_
      contract_discrepancy_le := ?_ }
  · intro k
    simpa using hf (k + m * d)
  · intro k
    rfl
  · intro B hB n
    -- Normalize the reduced discrepancy to the bundled offset discrepancy wrapper.
    have hrewrite :
        discrepancy (fun k => f (k + m * d)) d n = discOffset f d m n := by
      -- `discrepancy_shift_mul_simp` is the standard normal form for shifts by `m*d`.
      simpa using
        (discrepancy_shift_mul_simp (f := f) (m := m) (d := d) (n := n))
    -- Now discharge the bound using the supplied uniform `discOffset` bound.
    simpa [hrewrite] using hB n

/-- Consumer-facing rewrite: discrepancy of the reduced sequence equals bundled offset discrepancy.

This is the key normal-form bridge used by later stages.
-/
theorem discrepancy_eq_discOffset_via_contract (out : ReductionOutput f) (n : ℕ) :
    discrepancy out.g out.d n = discOffset f out.d out.m n := by
  -- `out.g_eq` identifies `out.g` with the canonical shift `fun k ↦ f (k + m*d)`.
  have hgfun : out.g = fun k => f (k + out.m * out.d) := by
    funext k
    simpa [out.g_eq]
  -- Now normalize discrepancy of a shift by `m*d`.
  simpa [hgfun] using
    (discrepancy_shift_mul_simp (f := f) (m := out.m) (d := out.d) (n := n))

/-- Convenience: pointwise discrepancy bounds for the reduced sequence are exactly pointwise bounds
on the bundled offset family. -/
theorem discrepancy_le_iff_discOffset_le (out : ReductionOutput f) (n B : ℕ) :
    discrepancy out.g out.d n ≤ B ↔ discOffset f out.d out.m n ≤ B := by
  simpa [out.discrepancy_eq_discOffset_via_contract (f := f) (n := n)]

/-- Bounded discrepancy along the reduced step is equivalent to a uniform bound on the bundled offset
discrepancy family.

This is a tiny packaging lemma: it lets consumers switch between the fixed-step normal form
(`discrepancy out.g out.d`) and the bundled offset normal form (`discOffset f out.d out.m`).
-/
theorem boundedDiscrepancyAlong_iff_exists_forall_discOffset_le (out : ReductionOutput f) :
    BoundedDiscrepancyAlong out.g out.d ↔
      ∃ B : ℕ, ∀ n : ℕ, discOffset f out.d out.m n ≤ B := by
  unfold BoundedDiscrepancyAlong
  constructor
  · rintro ⟨B, hB⟩
    refine ⟨B, ?_⟩
    intro n
    have h : discrepancy out.g out.d n ≤ B := hB n
    exact (out.discrepancy_le_iff_discOffset_le (f := f) (n := n) (B := B)).1 h
  · rintro ⟨B, hB⟩
    refine ⟨B, ?_⟩
    intro n
    have h : discOffset f out.d out.m n ≤ B := hB n
    exact (out.discrepancy_le_iff_discOffset_le (f := f) (n := n) (B := B)).2 h

/-- Stage-1 witness transport: reduced discrepancy-at-least is an affine-tail witness for `f`.

The affine nucleus is `apSumFrom f (m*d) d n`.
-/
theorem hasDiscrepancyAtLeastAlong_iff_exists_natAbs_apSumFrom_mul_gt (out : ReductionOutput f)
    (C : ℕ) :
    HasDiscrepancyAtLeastAlong out.g out.d C ↔
      ∃ n : ℕ, Int.natAbs (apSumFrom f (out.m * out.d) out.d n) > C := by
  unfold HasDiscrepancyAtLeastAlong
  constructor
  · rintro ⟨n, hn⟩
    have hn' : C < discOffset f out.d out.m n := by
      simpa [discrepancy_eq_discOffset_via_contract (f := f) (out := out) (n := n)] using hn
    have hsum : apSumOffset f out.d out.m n = apSumFrom f (out.m * out.d) out.d n := by
      simpa using
        (apSumFrom_tail_eq_apSumOffset_shift_add (f := f) (a := 0) (d := out.d) (m := out.m)
            (n := n)).symm

    have hn0 := hn'
    unfold discOffset at hn0
    have hnat :
        Int.natAbs (apSumOffset f out.d out.m n) =
          Int.natAbs (apSumFrom f (out.m * out.d) out.d n) := by
      simpa using congrArg Int.natAbs hsum
    rw [hnat] at hn0
    exact ⟨n, hn0⟩

  · rintro ⟨n, hn⟩
    have hsum : apSumFrom f (out.m * out.d) out.d n = apSumOffset f out.d out.m n := by
      simpa using
        (apSumFrom_tail_eq_apSumOffset_shift_add (f := f) (a := 0) (d := out.d) (m := out.m)
            (n := n))

    have hn0 := hn
    have hnat :
        Int.natAbs (apSumFrom f (out.m * out.d) out.d n) =
          Int.natAbs (apSumOffset f out.d out.m n) := by
      simpa using congrArg Int.natAbs hsum
    rw [hnat] at hn0

    have hn' : C < discOffset f out.d out.m n := by
      change C < Int.natAbs (apSumOffset f out.d out.m n)
      exact hn0

    refine ⟨n, ?_⟩
    have heq := discrepancy_eq_discOffset_via_contract (f := f) (out := out) (n := n)
    simpa [heq] using hn'

/-- Unboundedness of reduced discrepancy is equivalent to unboundedness of the bundled offset family.

The suffix `_lt` is legacy: the witness is `B < ...` (i.e. “greater than B”).
-/
@[deprecated "Use `unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt` (witnesses are of the form `B < discOffset ...`)." (since := "2026-03-24")]
theorem unboundedDiscrepancyAlong_iff_forall_exists_discOffset_lt (out : ReductionOutput f) :
    UnboundedDiscrepancyAlong out.g out.d ↔ (∀ B : ℕ, ∃ n : ℕ, B < discOffset f out.d out.m n) := by
  constructor
  · intro hunb B
    rcases hunb B with ⟨n, hn⟩
    refine ⟨n, ?_⟩
    simpa [discrepancy_eq_discOffset_via_contract (out := out) (n := n)] using hn
  · intro hunb B
    rcases hunb B with ⟨n, hn⟩
    refine ⟨n, ?_⟩
    simpa [discrepancy_eq_discOffset_via_contract (out := out) (n := n)] using hn

/-- Preferred naming for `unboundedDiscrepancyAlong_iff_forall_exists_discOffset_lt`.

The witnesses have the form `B < discOffset ...`, so we use the suffix `_gt` (“greater than B”).
-/
theorem unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt (out : ReductionOutput f) :
    UnboundedDiscrepancyAlong out.g out.d ↔ (∀ B : ℕ, ∃ n : ℕ, B < discOffset f out.d out.m n) := by
  constructor
  · intro hunb B
    rcases hunb B with ⟨n, hn⟩
    refine ⟨n, ?_⟩
    simpa [discrepancy_eq_discOffset_via_contract (out := out) (n := n)] using hn
  · intro hunb B
    rcases hunb B with ⟨n, hn⟩
    refine ⟨n, ?_⟩
    simpa [discrepancy_eq_discOffset_via_contract (out := out) (n := n)] using hn

/-- Packaged predicate form: reduced-step unbounded discrepancy is equivalent to unboundedness of the
bundled offset discrepancy family for `f`.
-/
theorem unboundedDiscrepancyAlong_iff_unboundedDiscOffset (out : ReductionOutput f) :
    UnboundedDiscrepancyAlong out.g out.d ↔ UnboundedDiscOffset f out.d out.m := by
  simpa [UnboundedDiscOffset] using
    (unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt (f := f) (out := out))

/-- Nucleus-level variant of `unboundedDiscrepancyAlong_iff_forall_exists_discOffset_lt`. -/
@[deprecated "Use `unboundedDiscrepancyAlong_iff_forall_exists_natAbs_apSumOffset_gt` (witnesses are of the form `B < Int.natAbs ...`)." (since := "2026-03-24")]
theorem unboundedDiscrepancyAlong_iff_forall_exists_natAbs_apSumOffset_lt (out : ReductionOutput f) :
    UnboundedDiscrepancyAlong out.g out.d ↔
      (∀ B : ℕ, ∃ n : ℕ, B < Int.natAbs (apSumOffset f out.d out.m n)) := by
  constructor
  · intro hunb
    have hdisc : ∀ B : ℕ, ∃ n : ℕ, B < discOffset f out.d out.m n :=
      (unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt (f := f) (out := out)).1 hunb
    intro B
    rcases hdisc B with ⟨n, hn⟩
    exact ⟨n, hn⟩
  · intro hunb
    refine
      (unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt (f := f) (out := out)).2 ?_
    intro B
    rcases hunb B with ⟨n, hn⟩
    exact ⟨n, hn⟩

/-- Preferred naming for `unboundedDiscrepancyAlong_iff_forall_exists_natAbs_apSumOffset_lt`.

The witnesses have the form `B < Int.natAbs ...`, so we use the suffix `_gt` (“greater than B”).
-/
theorem unboundedDiscrepancyAlong_iff_forall_exists_natAbs_apSumOffset_gt (out : ReductionOutput f) :
    UnboundedDiscrepancyAlong out.g out.d ↔
      (∀ B : ℕ, ∃ n : ℕ, B < Int.natAbs (apSumOffset f out.d out.m n)) := by
  constructor
  · intro hunb
    have hdisc : ∀ B : ℕ, ∃ n : ℕ, B < discOffset f out.d out.m n :=
      (unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt (f := f) (out := out)).1 hunb
    intro B
    rcases hdisc B with ⟨n, hn⟩
    exact ⟨n, hn⟩
  · intro hunb
    refine
      (unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt (f := f) (out := out)).2 ?_
    intro B
    rcases hunb B with ⟨n, hn⟩
    exact ⟨n, hn⟩

/-- If the bundled offset discrepancies are unbounded, then `f` cannot have globally bounded discrepancy. -/
theorem not_boundedDiscrepancy_of_forall_exists_discOffset_gt (out : ReductionOutput f)
    (hunb : ∀ B : ℕ, ∃ n : ℕ, B < discOffset f out.d out.m n) :
    ¬ BoundedDiscrepancy f := by
  intro hb
  -- Turn global boundedness into a reusable `Context`, then contradict the unbounded witness.
  let ctx : Context f := Context.ofBoundedDiscrepancy (f := f) hb
  have hbound : ∀ n : ℕ, discOffset f out.d out.m n ≤ 2 * ctx.B := by
    intro n
    simpa using
      (ctx.bound_discOffset_two_mul (f := f) (d := out.d) (m := out.m) (n := n) out.hd)
  rcases hunb (2 * ctx.B) with ⟨n, hn⟩
  exact (not_lt_of_ge (hbound n)) hn

/-- If reduced discrepancy along `out.d` is unbounded, then `f` cannot have globally bounded discrepancy.

This is just `not_boundedDiscrepancy_of_forall_exists_discOffset_gt` composed with the Stage-1
transport equivalence `unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt`.
-/
theorem not_boundedDiscrepancy_of_unboundedDiscrepancyAlong (out : ReductionOutput f)
    (hunb : UnboundedDiscrepancyAlong out.g out.d) :
    ¬ BoundedDiscrepancy f := by
  refine ReductionOutput.not_boundedDiscrepancy_of_forall_exists_discOffset_gt (f := f) (out := out) ?_
  exact (unboundedDiscrepancyAlong_iff_forall_exists_discOffset_gt (f := f) (out := out)).1 hunb

end ReductionOutput

/-- If some offset discrepancy family is unbounded, then `f` cannot have globally bounded discrepancy.

This is the global (non–Stage-1-specific) contrapositive used by later stages: global bounded
discrepancy implies a uniform bound on every `discOffset f d m`, so unboundedness of any one such
family yields a contradiction.
-/
theorem not_boundedDiscrepancy_of_forall_exists_discOffset_gt (f : ℕ → ℤ) {d m : ℕ} (hd : d > 0)
    (hunb : ∀ B : ℕ, ∃ n : ℕ, B < discOffset f d m n) :
    ¬ BoundedDiscrepancy f := by
  intro hb
  -- Turn global boundedness into a reusable `Context`, then contradict the unbounded witness.
  let ctx : Context f := Context.ofBoundedDiscrepancy (f := f) hb
  have hbound : ∀ n : ℕ, discOffset f d m n ≤ 2 * ctx.B := by
    intro n
    simpa using (ctx.bound_discOffset_two_mul (f := f) (d := d) (m := m) (n := n) hd)
  rcases hunb (2 * ctx.B) with ⟨n, hn⟩
  exact (not_lt_of_ge (hbound n)) hn

/-- If an offset discrepancy family is unbounded (packaged form), then `f` cannot have globally
bounded discrepancy.

This is just `not_boundedDiscrepancy_of_forall_exists_discOffset_gt` with `UnboundedDiscOffset`
unfolded.
-/
theorem not_boundedDiscrepancy_of_unboundedDiscOffset (f : ℕ → ℤ) {d m : ℕ} (hd : d > 0)
    (hunb : UnboundedDiscOffset f d m) :
    ¬ BoundedDiscrepancy f := by
  refine
    Tao2015.not_boundedDiscrepancy_of_forall_exists_discOffset_gt (f := f) (d := d) (m := m) hd ?_
  simpa [UnboundedDiscOffset] using hunb

end Tao2015

end MoltResearch
