import MoltResearch.Discrepancy.Affine
import MoltResearch.Discrepancy.Offset

/-!
# Discrepancy: translation (additive reindexing) lemmas

(Generated by Forge.)
-/

namespace MoltResearch

lemma apSumFrom_shift_add (f : ℕ → ℤ) (k a d n : ℕ) :
  apSumFrom (fun x => f (x + k)) a d n = apSumFrom f (a + k) d n := by
  unfold apSumFrom
  refine Finset.sum_congr rfl ?_
  intro i hi
  simp [Nat.add_comm, Nat.add_assoc]

/-!
### Translation bookkeeping for affine starts

These lemmas let you *move a translation* between the affine start parameter and the summand.

They are thin wrappers around `apSumFrom_shift_add`, but having both orientations available keeps
rewrite pipelines from accumulating `.symm` noise.
-/

/-- Move an addition on the start parameter into the summand shift.

Canonical “pull translation out of the start” form:

`apSumFrom f (a + b) d n = apSumFrom (fun t => f (t + b)) a d n`.
-/
lemma apSumFrom_start_add_eq_shift_add (f : ℕ → ℤ) (a b d n : ℕ) :
    apSumFrom f (a + b) d n = apSumFrom (fun t => f (t + b)) a d n := by
  simpa using (apSumFrom_shift_add (f := f) (k := b) (a := a) (d := d) (n := n)).symm

/-- Inverse orientation of `apSumFrom_start_add_eq_shift_add`.

Canonical “push translation into the start” form:

`apSumFrom (fun t => f (t + b)) a d n = apSumFrom f (a + b) d n`.
-/
lemma apSumFrom_shift_add_eq_start_add (f : ℕ → ℤ) (a b d n : ℕ) :
    apSumFrom (fun t => f (t + b)) a d n = apSumFrom f (a + b) d n := by
  simpa using (apSumFrom_shift_add (f := f) (k := b) (a := a) (d := d) (n := n))


/-- Variant of `apSumFrom_shift_add` for translated functions written in the `k + x` form.

This is occasionally convenient when the ambient goal prefers a “constant on the left” convention.
-/
lemma apSumFrom_shift_add_left (f : ℕ → ℤ) (k a d n : ℕ) :
  apSumFrom (fun x => f (k + x)) a d n = apSumFrom f (k + a) d n := by
  have hfun : (fun x => f (k + x)) = fun x => f (x + k) := by
    funext x
    simp [Nat.add_comm]
  -- Reduce to `apSumFrom_shift_add` and then normalize `a + k` ↔ `k + a`.
  simpa [hfun, Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using
    (apSumFrom_shift_add (f := f) (k := k) (a := a) (d := d) (n := n))


lemma apSum_shift_add (f : ℕ → ℤ) (k d n : ℕ) :
  apSum (fun x => f (x + k)) d n = apSumFrom f k d n := by
  calc
    apSum (fun x => f (x + k)) d n
        = apSumFrom (fun x => f (x + k)) 0 d n := by
            simpa using (apSum_eq_apSumFrom (f := fun x => f (x + k)) (d := d) (n := n))
    _ = apSumFrom f (0 + k) d n := by
            simpa using (apSumFrom_shift_add (f := f) (k := k) (a := 0) (d := d) (n := n))
    _ = apSumFrom f k d n := by simp


/-!
## Normalization of nested shifts

(Moved to `MoltResearch.Discrepancy.Basic` so it is available to the nucleus rewrite pipeline
without importing `Translate`.)
-/

/-- Commute an additive translation under `apSum`. 

This is a lightweight normal-form lemma: it lets you switch between the binder conventions
`fun k => f (a + k)` and `fun k => f (k + a)` without doing a manual `funext` rewrite.

We do *not* mark this as `[simp]`: it is intended as an explicit normalization step when you want
a translation-friendly `k + const` summand shape.
-/
lemma apSum_shift_comm (f : ℕ → ℤ) (a d n : ℕ) :
    apSum (fun k => f (a + k)) d n = apSum (fun k => f (k + a)) d n := by
  unfold apSum
  refine Finset.sum_congr rfl ?_
  intro i hi
  simp [Nat.add_comm]

/-- Commute an additive translation under `apSumFrom`.

This is the affine analogue of `apSum_shift_comm`: it lets you switch between the binder
conventions `fun x => f (a + x)` and `fun x => f (x + a)` without doing a manual `funext` rewrite.

We do *not* mark this as `[simp]`: it is intended as an explicit normalization step when you want
a translation-friendly `x + const` summand shape.
-/
lemma apSumFrom_shift_comm (f : ℕ → ℤ) (a k d n : ℕ) :
    apSumFrom (fun x => f (a + x)) k d n = apSumFrom (fun x => f (x + a)) k d n := by
  unfold apSumFrom
  refine Finset.sum_congr rfl ?_
  intro i hi
  simp [Nat.add_comm]

/-- Commute the argument order in a translated function under `apSumOffset`.

This is a tiny normalization lemma: it avoids a separate `funext` rewrite when you want to switch
between the binder conventions `fun x => f (x + k)` and `fun x => f (k + x)`.

We do *not* mark this as `[simp]`: it is intended as an explicit rewrite step.
-/
lemma apSumOffset_shift_add_comm (f : ℕ → ℤ) (k d m n : ℕ) :
    apSumOffset (fun x => f (x + k)) d m n = apSumOffset (fun x => f (k + x)) d m n := by
  unfold apSumOffset
  refine Finset.sum_congr rfl ?_
  intro i hi
  simp [Nat.add_comm, Nat.add_left_comm, Nat.add_assoc]


-- (moved to `Discrepancy/Affine.lean`)

lemma apSumOffset_shift_add (f : ℕ → ℤ) (k d m n : ℕ) :
  apSumOffset (fun x => f (x + k)) d m n = apSumFrom f (m * d + k) d n := by
  calc
    apSumOffset (fun x => f (x + k)) d m n
        = apSumFrom (fun x => f (x + k)) (m * d) d n := by
            simpa using
              (apSumOffset_eq_apSumFrom (f := fun x => f (x + k)) (d := d) (m := m) (n := n))
    _ = apSumFrom f (m * d + k) d n := by
            simpa using (apSumFrom_shift_add (f := f) (k := k) (a := m * d) (d := d) (n := n))


/-- This is a convenience lemma: it avoids an extra `funext` rewrite step (to commute `k + x` into
`x + k`) while keeping the affine start parameter in the `m*d + k` normal form.

Proof: commute the translation under `apSumOffset` using `apSumOffset_shift_add_comm`, then apply
`apSumOffset_shift_add`.
-/
lemma apSumOffset_shift_add_left (f : ℕ → ℤ) (k d m n : ℕ) :
  apSumOffset (fun x => f (k + x)) d m n = apSumFrom f (m * d + k) d n := by
  calc
    apSumOffset (fun x => f (k + x)) d m n
        = apSumOffset (fun x => f (x + k)) d m n := by
            simpa using
              (apSumOffset_shift_add_comm (f := f) (k := k) (d := d) (m := m) (n := n)).symm
    _ = apSumFrom f (m * d + k) d n := by
            simpa using (apSumOffset_shift_add (f := f) (k := k) (d := d) (m := m) (n := n))


/-- This is a small normal-form lemma: it avoids a separate rewrite step commuting `m*d + k` into
`k + m*d` when you want the start parameter to match a “shift-then-offset” reading.
-/
lemma apSumOffset_shift_add_start_add_left (f : ℕ → ℤ) (k d m n : ℕ) :
  apSumOffset (fun x => f (x + k)) d m n = apSumFrom f (k + m * d) d n := by
  have h := apSumOffset_shift_add (f := f) (k := k) (d := d) (m := m) (n := n)
  -- Normalize the affine start parameter `m*d + k` into `k + m*d`.
  simpa [Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using h

/-- This is a convenience lemma: it rewrites an offset sum on a shifted sequence
`apSumOffset (fun k => f (k + a)) d m n` into a homogeneous AP sum on a further-shifted sequence
with the *same* step size `d`.

The resulting summand is written in the translation-friendly `k + const` form.
-/
lemma apSumOffset_shift_add_eq_apSum_shift_add (f : ℕ → ℤ) (a d m n : ℕ) :
    apSumOffset (fun k => f (k + a)) d m n = apSum (fun k => f (k + (a + m * d))) d n := by
  -- Start from the generic offset → shifted-homogeneous normal form.
  simpa [Nat.add_assoc, Nat.add_left_comm, Nat.add_comm] using
    (apSumOffset_eq_apSum_shift_add (f := fun k => f (k + a)) (d := d) (m := m) (n := n))

/-- Add-left variant of `apSumOffset_shift_add_eq_apSum_shift_add`.

This is the same convenience lemma, but in the `const + k` convention on the resulting `apSum`:

`apSumOffset (fun k => f (k + a)) d m n = apSum (fun k => f ((a + m*d) + k)) d n`.

This avoids an extra rewrite step commuting the translation constant under binders when your
surrounding development already prefers `const + x` summand shapes.
-/
lemma apSumOffset_shift_add_eq_apSum_shift_add_left (f : ℕ → ℤ) (a d m n : ℕ) :
    apSumOffset (fun k => f (k + a)) d m n = apSum (fun k => f ((a + m * d) + k)) d n := by
  calc
    apSumOffset (fun k => f (k + a)) d m n
        = apSum (fun k => f (k + (a + m * d))) d n := by
            simpa using
              (apSumOffset_shift_add_eq_apSum_shift_add (f := f) (a := a) (d := d) (m := m)
                (n := n))
    _ = apSum (fun k => f ((a + m * d) + k)) d n := by
            simpa using (apSum_shift_comm (f := f) (a := a + m * d) (d := d) (n := n)).symm

/-- Inverse orientation of `apSumOffset_shift_add_eq_apSum_shift_add_left`. -/
lemma apSum_shift_add_left_eq_apSumOffset_shift_add (f : ℕ → ℤ) (a d m n : ℕ) :
    apSum (fun k => f ((a + m * d) + k)) d n = apSumOffset (fun k => f (k + a)) d m n := by
  simpa using
    (apSumOffset_shift_add_eq_apSum_shift_add_left (f := f) (a := a) (d := d) (m := m)
      (n := n)).symm

/-- Add-left variant of `apSumOffset_shift_add_eq_apSum_shift_add`.

This is the same convenience lemma, but in the `a + k` convention:

`apSumOffset (fun k => f (a + k)) d m n = apSum (fun k => f ((a + m*d) + k)) d n`.

We keep both orientations available since `simp` often behaves better when we avoid commuting
addition under binders.
-/
lemma apSumOffset_shift_add_left_eq_apSum_shift_add_left (f : ℕ → ℤ) (a d m n : ℕ) :
    apSumOffset (fun k => f (a + k)) d m n = apSum (fun k => f ((a + m * d) + k)) d n := by
  -- Start from the generic offset → shifted-homogeneous normal form (`m*d + k`) and reassociate.
  simpa [Nat.add_assoc, Nat.add_left_comm, Nat.add_comm] using
    (apSumOffset_eq_apSum_shift (f := fun k => f (a + k)) (d := d) (m := m) (n := n))

/-- Inverse orientation of `apSumOffset_shift_add_eq_apSum_shift_add`.

This rewrites a homogeneous AP sum on a shifted sequence back into an `apSumOffset` on the
less-shifted sequence.
-/
lemma apSum_shift_add_eq_apSumOffset_shift_add (f : ℕ → ℤ) (a d m n : ℕ) :
    apSum (fun k => f (k + (a + m * d))) d n = apSumOffset (fun k => f (k + a)) d m n := by
  simpa using
    (apSumOffset_shift_add_eq_apSum_shift_add (f := f) (a := a) (d := d) (m := m) (n := n)).symm

/-- Inverse orientation of `apSumOffset_shift_add_left_eq_apSum_shift_add_left`. -/
lemma apSum_shift_add_left_eq_apSumOffset_shift_add_left (f : ℕ → ℤ) (a d m n : ℕ) :
    apSum (fun k => f ((a + m * d) + k)) d n = apSumOffset (fun k => f (a + k)) d m n := by
  simpa using
    (apSumOffset_shift_add_left_eq_apSum_shift_add_left (f := f) (a := a) (d := d) (m := m)
      (n := n)).symm

/-!
Note: the common `a = 0` specializations of the inverse shift-add lemmas (e.g.
`apSum (fun k => f (k + m*d)) d n = apSumOffset f d m n`) live in `Discrepancy/Offset.lean`
as `apSum_shift_add_eq_apSumOffset` / `apSum_shift_eq_apSumOffset`.

We keep the more general `a`-parameterized versions here since they are the natural glue for
composing translations.
-/

lemma HasDiscrepancyAtLeast.of_shift_add {f : ℕ → ℤ} {k C : ℕ} :
  HasDiscrepancyAtLeast (fun x => f (x + k)) C → HasAffineDiscrepancyAtLeast f C := by
  rintro ⟨d, n, hd, hgt⟩
  refine ⟨k, d, n, hd, ?_⟩
  simpa [apSum_shift_add] using hgt

/-! ### Witness-level normal form for shifted sequences

Track B often wants shifted sequences to be expressed using the offset-sum nucleus `apSumOffset`
so that start-index shifts can be handled canonically via `apSumOffset_shift_start_add*`.

The lemma below is a thin wrapper that turns a `HasDiscrepancyAtLeast` witness for the shifted
sequence `k ↦ f (k + a)` into the corresponding offset-sum witness.

(We do not claim any invariance result for `HasDiscrepancyAtLeast f C`; this is only a
normal-form rewrite of the witness expression.)
-/

/-- Normal form: a witness for `HasDiscrepancyAtLeast (k ↦ f (k + a)) C` can be written using
`apSumOffset (k ↦ f (k + a)) d 0 n`.

This is convenient when downstream steps want to rewrite start-index shifts via
`apSumOffset_shift_start_add*`.
-/
lemma HasDiscrepancyAtLeast_shift_add_iff_exists_apSumOffset_zero_start {f : ℕ → ℤ} {a C : ℕ} :
    HasDiscrepancyAtLeast (fun k => f (k + a)) C ↔
      ∃ d n : ℕ, d > 0 ∧ Int.natAbs (apSumOffset (fun k => f (k + a)) d 0 n) > C := by
  -- This is just `HasDiscrepancyAtLeast_iff_exists_apSumOffset_zero_start` applied to the shifted function.
  simpa using
    (HasDiscrepancyAtLeast_iff_exists_apSumOffset_zero_start (f := fun k => f (k + a)) (C := C))

/-! ### Translation normal form via div/mod (witness-level)

When working with translated sequences `k ↦ f (k + a)`, it is often useful to rewrite a witness
`apSum (k ↦ f (k + a)) d n` into an offset-sum where the translation constant is reduced modulo
`d`, and the quotient `a / d` is recorded as a start-index shift.

This aligns well with the canonical start-shift normalization lemmas
`apSumOffset_shift_start_add*`.
-/

/-- Normal form: rewrite a translated AP sum using `Nat.div`/`Nat.mod`.

For any `a d n`:

`apSum (fun k => f (k + a)) d n = apSumOffset (fun t => f (t + (a % d))) d (a / d) n`.

Intuition: write `a = (a / d) * d + (a % d)` and absorb the quotient as a start-index shift.
-/
lemma apSum_shift_add_eq_apSumOffset_div_mod (f : ℕ → ℤ) (a d n : ℕ) :
    apSum (fun k => f (k + a)) d n =
      apSumOffset (fun t => f (t + (a % d))) d (a / d) n := by
  -- Start from the generic inverse shift-add lemma in the `a + k` convention.
  have h :=
    (apSum_shift_add_left_eq_apSumOffset_shift_add_left (f := f) (a := a % d)
        (d := d) (m := a / d) (n := n))
  -- Convert the `apSumOffset` side to the `k + const` binder convention.
  have hoff :
      apSumOffset (fun k => f (a % d + k)) d (a / d) n =
        apSumOffset (fun k => f (k + a % d)) d (a / d) n := by
    simpa using
      (apSumOffset_shift_add_comm (f := f) (k := a % d) (d := d) (m := a / d) (n := n)).symm
  -- Replace `a` by `a % d + (a / d) * d` (using `Nat.div_add_mod`).
  have ha : a % d + (a / d) * d = a := by
    -- `Nat.div_add_mod` is `d * (a / d) + a % d = a`.
    simpa [Nat.add_comm, Nat.add_left_comm, Nat.add_assoc, Nat.mul_comm] using
      (Nat.div_add_mod a d)
  have ha' : a = a % d + (a / d) * d := ha.symm
  calc
    apSum (fun k => f (k + a)) d n
        = apSum (fun k => f (a + k)) d n := by
            simpa using (apSum_shift_comm (f := f) (a := a) (d := d) (n := n)).symm
    _ = apSum (fun k => f ((a % d + (a / d) * d) + k)) d n := by
            have hfun : (fun k => f (a + k)) = fun k => f ((a % d + (a / d) * d) + k) := by
              funext k
              have hk : a + k = (a % d + (a / d) * d) + k := by
                simpa using congrArg (fun t => t + k) ha'
              simpa [hk]
            simpa [hfun]
    _ = apSumOffset (fun k => f (a % d + k)) d (a / d) n := by
            exact h
    _ = apSumOffset (fun k => f (k + a % d)) d (a / d) n := by
            simpa using hoff

/-- Normal form: rewrite an affine AP sum `apSumFrom` into an `apSumOffset` div/mod normal form.

`apSumFrom f a d n = apSumOffset (fun t => f (t + (a % d))) d (a / d) n`.

Intuition: view `apSumFrom f a d n` as `apSum (k ↦ f (k + a)) d n` and then apply
`apSum_shift_add_eq_apSumOffset_div_mod`.
-/
lemma apSumFrom_eq_apSumOffset_div_mod (f : ℕ → ℤ) (a d n : ℕ) (hd : d > 0) :
    apSumFrom f a d n =
      apSumOffset (fun t => f (t + (a % d))) d (a / d) n := by
  -- The hypothesis `hd` is included for API consistency with other div/mod normal forms.
  have hd' : d > 0 := hd
  clear hd'
  -- Rewrite to a shifted `apSum`, then normalize via div/mod.
  simpa [apSumFrom_eq_apSum_shift_add] using
    (apSum_shift_add_eq_apSumOffset_div_mod (f := f) (a := a) (d := d) (n := n))

/-- Normal form (mod step): reduce a translation inside an `apSumOffset` witness using `Nat.div`/`Nat.mod`.

`apSumOffset (fun k => f (k + a)) d m n = apSumOffset (fun k => f (k + (a % d))) d (m + a / d) n`.

Intuition: write `a = (a / d) * d + (a % d)` and absorb the quotient into the start index.
-/
lemma apSumOffset_shift_add_eq_apSumOffset_div_mod (f : ℕ → ℤ) (a d m n : ℕ) (hd : d > 0) :
    apSumOffset (fun k => f (k + a)) d m n =
      apSumOffset (fun k => f (k + (a % d))) d (m + a / d) n := by
  -- Compute the adjusted translation constant.
  have hconst' : (m + a / d) * d + a % d = m * d + a := by
    -- Expand `(m + a/d) * d` and use `Nat.div_add_mod`.
    calc
      (m + a / d) * d + a % d
          = (m * d + (a / d) * d) + a % d := by
              simp [Nat.add_mul, Nat.add_assoc, Nat.add_left_comm, Nat.add_comm]
      _ = m * d + ((a / d) * d + a % d) := by
              simp [Nat.add_assoc, Nat.add_left_comm, Nat.add_comm]
      _ = m * d + (d * (a / d) + a % d) := by
              simp [Nat.mul_comm, Nat.add_assoc]
      _ = m * d + a := by
              simpa [Nat.add_assoc] using congrArg (fun t => m * d + t) (Nat.div_add_mod a d)
  have hconst : m * d + a = (m + a / d) * d + a % d := by
    simpa using hconst'.symm
  -- Rewrite both sides into shifted `apSum` form and use `hconst`.
  -- (The hypothesis `hd` is included for API consistency with other div/mod normal forms.)
  have hd' : d > 0 := hd
  clear hd'
  -- LHS
  have hL : apSumOffset (fun k => f (k + a)) d m n = apSum (fun k => f (k + (m * d + a))) d n := by
    simp [apSumOffset_eq_apSum_shift_add, Nat.add_assoc, Nat.add_left_comm, Nat.add_comm]
  -- RHS
  have hR : apSumOffset (fun k => f (k + (a % d))) d (m + a / d) n =
      apSum (fun k => f (k + ((m + a / d) * d + a % d))) d n := by
    simp [apSumOffset_eq_apSum_shift_add, Nat.add_assoc, Nat.add_left_comm, Nat.add_comm]
  -- Compare the shifted `apSum` expressions.
  -- (We avoid commuting addition under binders by keeping the `k + const` convention.)
  rw [hL, hR]
  unfold apSum
  refine Finset.sum_congr rfl ?_
  intro i hi
  -- Use the constant equality inside the binder.
  simp [hconst, Nat.add_assoc, Nat.add_left_comm, Nat.add_comm]

/-- Alias for `apSumOffset_shift_add_eq_apSumOffset_div_mod`.

This is the translation-normal-form rule for an `apSumOffset` on a shifted sequence:
reduce the shift `a` modulo the step size `d` and absorb the quotient `a / d` into the
start index.
-/
lemma apSumOffset_shift_add_mod (f : ℕ → ℤ) (a d m n : ℕ) (hd : d > 0) :
    apSumOffset (fun k => f (k + a)) d m n =
      apSumOffset (fun k => f (k + (a % d))) d (m + a / d) n := by
  simpa using
    (apSumOffset_shift_add_eq_apSumOffset_div_mod (f := f) (a := a) (d := d) (m := m) (n := n) hd)

/-- Witness-level normal form: rewrite a translated discrepancy witness into `apSumOffset`
with translation reduced modulo `d`.

If `HasDiscrepancyAtLeast (fun k => f (k + a)) C` holds, then there exist `d n` such that
`Int.natAbs (apSumOffset (fun t => f (t + (a % d))) d (a / d) n) > C`.
-/
lemma HasDiscrepancyAtLeast_shift_add_exists_apSumOffset_div_mod {f : ℕ → ℤ} {a C : ℕ} :
    HasDiscrepancyAtLeast (fun k => f (k + a)) C →
      ∃ d n : ℕ, d > 0 ∧ Int.natAbs (apSumOffset (fun t => f (t + (a % d))) d (a / d) n) > C := by
  rintro ⟨d, n, hd, hgt⟩
  refine ⟨d, n, hd, ?_⟩
  -- Rewrite the witness sum into the offset-sum div/mod normal form.
  simpa [apSum_shift_add_eq_apSumOffset_div_mod (f := f) (a := a) (d := d) (n := n)] using hgt

/-- Iff normal form: `HasDiscrepancyAtLeast (k ↦ f (k + a)) C` can be expressed using the
`div/mod`-reduced translation inside an `apSumOffset` witness.

This aligns with the start-shift normalization lemmas `apSumOffset_shift_start_add*`.
-/
lemma HasDiscrepancyAtLeast_shift_add_iff_exists_apSumOffset_div_mod {f : ℕ → ℤ} {a C : ℕ} :
    HasDiscrepancyAtLeast (fun k => f (k + a)) C ↔
      ∃ d n : ℕ, d > 0 ∧ Int.natAbs (apSumOffset (fun t => f (t + (a % d))) d (a / d) n) > C := by
  constructor
  · intro h
    exact HasDiscrepancyAtLeast_shift_add_exists_apSumOffset_div_mod (f := f) (a := a) (C := C) h
  · rintro ⟨d, n, hd, hgt⟩
    refine ⟨d, n, hd, ?_⟩
    simpa [apSum_shift_add_eq_apSumOffset_div_mod (f := f) (a := a) (d := d) (n := n)] using hgt

/-- Variant of `HasDiscrepancyAtLeast.of_shift_add` for translated functions written in the `k + x`
form. -/
lemma HasDiscrepancyAtLeast.of_shift_add_left {f : ℕ → ℤ} {k C : ℕ} :
  HasDiscrepancyAtLeast (fun x => f (k + x)) C → HasAffineDiscrepancyAtLeast f C := by
  have hfun : (fun x => f (k + x)) = fun x => f (x + k) := by
    funext x
    simp [Nat.add_comm]
  simpa [hfun] using (HasDiscrepancyAtLeast.of_shift_add (f := f) (k := k) (C := C))

lemma HasAffineDiscrepancyAtLeast.of_shift_add {f : ℕ → ℤ} {k C : ℕ} :
  HasAffineDiscrepancyAtLeast (fun x => f (x + k)) C → HasAffineDiscrepancyAtLeast f C := by
  rintro ⟨a, d, n, hd, hgt⟩
  refine ⟨a + k, d, n, hd, ?_⟩
  simpa [apSumFrom_shift_add] using hgt

/-- Variant of `HasAffineDiscrepancyAtLeast.of_shift_add` for translated functions written in the
`k + x` form. -/
lemma HasAffineDiscrepancyAtLeast.of_shift_add_left {f : ℕ → ℤ} {k C : ℕ} :
  HasAffineDiscrepancyAtLeast (fun x => f (k + x)) C → HasAffineDiscrepancyAtLeast f C := by
  have hfun : (fun x => f (k + x)) = fun x => f (x + k) := by
    funext x
    simp [Nat.add_comm]
  simpa [hfun] using (HasAffineDiscrepancyAtLeast.of_shift_add (f := f) (k := k) (C := C))





/-!
## Boundedness under sequence translation (step-one wrapper)

Checklist item: `Problems/erdos_discrepancy.md` (Track B) —
“Boundedness under sequence translation”.

In our normal forms, `discAlong f d n` is implemented as `discOffset f d 0 n`. The `discOffset`
API already has clean shift lemmas for translations by multiples of `d`.

This section packages the special case relevant to “sequence translation” in the *step-one* view:
shifting the input sequence by `a` corresponds exactly to increasing the offset parameter `m` by
`a` when `d = 1`.
-/

/-- Step-one translation wrapper: along-`1` discrepancy of a shifted sequence is the offset
  discrepancy at start `a`.

This is the clean bridge between
`discAlong (fun k => f (k + a)) 1 n`
and
`discOffset f 1 a n`.
-/
lemma discAlong_shift_add_step_one_eq_discOffset (f : ℕ → ℤ) (a n : ℕ) :
    discAlong (fun k => f (k + a)) 1 n = discOffset f 1 a n := by
  -- `discAlong g 1 n = discOffset g 1 0 n` by definition, and
  -- `discOffset f 1 a n = discOffset (fun k => f (k + a*1)) 1 0 n` by `discOffset_eq_discOffset_shift_add`.
  simpa [discAlong, Nat.mul_one] using
    (discOffset_eq_discOffset_shift_add (f := f) (d := 1) (m := a) (n := n)).symm

/-- Track-B wrapper: boundedness along `1` for a translated sequence is equivalent to
boundedness of `discOffset` at start `a`.

This is the packaged form used to “shift origins” without rebuilding witnesses.
-/
theorem boundedDiscrepancyAlong_shift_add_step_one_iff_forall_le_discOffset_le
    (f : ℕ → ℤ) (a len B : ℕ) :
    BoundedDiscrepancyAlong (fun k => f (k + a)) 1 len B ↔
      ∀ n : ℕ, n ≤ len → discOffset f 1 a n ≤ B := by
  constructor
  · intro h n hn
    simpa [discAlong_shift_add_step_one_eq_discOffset (f := f) (a := a) (n := n)] using h n hn
  · intro h n hn
    have hn' : discOffset f 1 a n ≤ B := h n hn
    simpa [discAlong_shift_add_step_one_eq_discOffset (f := f) (a := a) (n := n)] using hn'


end MoltResearch
