#!/usr/bin/env python3
"""Provenance report: who (human or agent) contributed what, from git history.

The repo's thesis is mass agent collaboration with CI as the arbiter; this script makes
that history a queryable artifact instead of archaeology.  Attribution sources, in
order of reliability:

1. `Co-Authored-By:` trailers (agents add these; they survive squash-merges),
2. merged-PR head-branch prefixes (`vex/`, `codex/`, `claude/`, ... — needs `gh`),
3. raw git author identities (weakest: agents often commit under a human's git user).

Usage:
    python3 scripts/provenance_report.py [--md] [--since YYYY-MM-DD]

`--md` emits a Markdown report (used to refresh Learning/PROVENANCE.md); the default is
a plain-text summary.  PR-prefix data is skipped gracefully when `gh` is unavailable.
"""

import argparse
import collections
import shutil
import subprocess


def _git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], capture_output=True, text=True, check=True
    ).stdout


def author_counts(since: str | None) -> collections.Counter:
    args = ["log", "--format=%an"]
    if since:
        args.append(f"--since={since}")
    return collections.Counter(_git(*args).splitlines())


def coauthor_counts(since: str | None) -> collections.Counter:
    args = ["log", "--format=%(trailers:key=Co-Authored-By,valueonly)"]
    if since:
        args.append(f"--since={since}")
    lines = [l.strip() for l in _git(*args).splitlines() if l.strip()]
    return collections.Counter(lines)


def pr_prefix_counts() -> collections.Counter | None:
    if shutil.which("gh") is None:
        return None
    try:
        out = subprocess.run(
            ["gh", "pr", "list", "--state", "merged", "--limit", "1000",
             "--json", "headRefName", "-q", ".[].headRefName"],
            capture_output=True, text=True, check=True, timeout=60,
        ).stdout
    except Exception:
        return None
    counts: collections.Counter = collections.Counter()
    for ref in out.splitlines():
        prefix = ref.split("/", 1)[0] if "/" in ref else "(unprefixed)"
        counts[prefix] += 1
    return counts


def render(counts: collections.Counter, title: str, md: bool, top: int = 15) -> str:
    lines = []
    if md:
        lines.append(f"### {title}\n")
        lines.append("| Identity | Count |")
        lines.append("|---|---|")
        for name, n in counts.most_common(top):
            lines.append(f"| {name} | {n} |")
    else:
        lines.append(f"== {title}")
        for name, n in counts.most_common(top):
            lines.append(f"  {n:6d}  {name}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--md", action="store_true", help="emit Markdown")
    ap.add_argument("--since", default=None, help="restrict to commits since a date")
    ns = ap.parse_args()

    out = []
    if ns.md:
        out.append("# Contribution provenance\n")
        out.append("Generated by `scripts/provenance_report.py`. Attribution comes from")
        out.append("`Co-Authored-By` trailers (most reliable — agents: always add yours,")
        out.append("plus a session link), merged-PR branch prefixes, and git authors.\n")
    out.append(render(coauthor_counts(ns.since),
                      "Co-Authored-By trailers (commits)", ns.md))
    prs = pr_prefix_counts()
    if prs is not None:
        out.append(render(prs, "Merged PRs by branch prefix", ns.md))
    out.append(render(author_counts(ns.since), "Git author identities (commits)", ns.md))
    print("\n".join(out))


if __name__ == "__main__":
    main()
